### ISSUE TITLE
POST always has content_type 'application/x-www-form-urlencoded'?

### ISSUE THREAD

**Issue by ceralena** [rest-client/rest-client#104]
I'm using Rest-Client to submit a simple POST to CouchDB, with content-type application/json. Rest-Client's UrlEncoded class has this code, though:

``` ruby
def headers
  super.merge({'Content-Type' => 'application/x-www-form-urlencoded'})
end
```

Is there a way around this? I don't see why the content type should be messed with if the developer has specified it.

I'm calling it like this:

``` ruby
RestClient.post uri, payload, headers, &block
```

Here are the parameters:

``` ruby
URI: http://cerales:password@localhost:5984/testing
Payload: {"dan":true,"yep":1}
Headers: {:content_type=>:json, :accept=>:json}
```

Payload is a string, but I've tried it with a hash too.

**Comment by matkruse** [comment]
The problem seems to be that if the payload is being passed in as a hash,  then the content-type is overridden.  Unless you want to pass a header overridden message back to the user due to the payload structure, I think you can close this issue.  @quigebo is right on.

**Comment by ab** [comment]
Yeah, it seems possible that rest-client should raise an exception if you pass a `Content-Type` header and also a Hash for the payload, since that combination is incompatible. Also possible it would be less intrusive to simply `warn()`.

**Comment by ryannmicua** [comment]
Would be nice if this was at least in the examples.

One wouldn't expect to have to convert a hash to a json string when all the other examples show the payload being a hash. Also, one would expect to be able to "override" the content type (and other headers) and not be overridden without the user knowing about it.

**Comment by cazador4** [comment]
+1

**Comment by ioquatix** [comment]
> Yeah, it seems possible that rest-client should raise an exception if you pass a Content-Type header and also a Hash for the payload, since that combination is incompatible. Also possible it would be less intrusive to simply warn().

Why not derive the encoding of the hash from the content_type specified?

**Comment by udyk-dev** [comment]
+1
