### ISSUE TITLE
Can't get POST to applications web interface just right.

### ISSUE THREAD

**Issue by Kitsoran** [rest-client/rest-client#107]
I'm trying to upload a .torrent to µTorrent using its web interface, so I can write a library for interacting with it. I can't seem to get the call just right, even managed to cause a DoS on the app. A pointer would be greatly appreciated. I've uploaded a pcap and decode of a good call.

http://www.mediafire.com/?9xp8zcwwbtkre63

https://gist.github.com/1503943

**Comment by ab** [comment]
Closing this since it's super stale, but feel free to reopen if this is still an issue.
