### ISSUE TITLE
restclient doesn't properly terminate http connection

### ISSUE THREAD

**Issue by lhahne** [rest-client/rest-client#112]
It appears that restclient doesn't properly terminate http connections and we get problems after it eats all available tcp ports. This has been reported also at https://github.com/joschi/graylog2-mongo-es-migrator/issues/1

**Comment by ab** [comment]
This doesn't sound like a bug in rest-client. `TIME_WAIT` is the TCP connection state where the local side of the connection is _closed_, but the kernel is waiting around with the connection not fully recycled just in case.

http://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux.html

**Comment by HorizonShadow** [comment]
Hi,

I'm running into this issue now, and I'm definitely not running >1000 requests a second. 

Basically what's happening is every time I do a RestClient.get, it runs, gets the request, and closes.

However when the client socket closes, it stays open for 240 seconds waiting to see if the server has anything else to say. If you have enough of these sockets waiting, you'll run out of available ports and hit this error.

I found a blog for .net that seems to have a solution for this problem, but I have no sweet clue if it's possible to implement with RestClient.

https://westerndevs.com/Deployment/httpclientwrong/
