### ISSUE TITLE
Pass request args into get, put, post, etc.

### ISSUE THREAD

**Issue by sbowman** [rest-client/rest-client#114]
It would be nice if we could pass the supported RestClient::Request args, like :timeout, into the get, post, etc. methods and have them passed along to Request.  Otherwise it seems like we have to create a custom get method that calls RestClient::Request directly if we want to adjust the settings.  Or is there some other way to do this I'm not seeing in the code?

**Comment by ab** [comment]
The API design for RestClient is very bad, and there's truly no way to pass complex settings to the `RestClient.get` and similar helpers.

You'll have to call `RestClient::Request.execute(method: :get, ...)` in order to adjust the settings, or create your own get method as you describe.
