### ISSUE TITLE
Query string params do not encode nested objects

### ISSUE THREAD

**Issue by boucher** [rest-client/rest-client#125]
Trying to have restclient create the appropriate query string when the params hash contains a nested hash or nested array does not produce the right result. It should behave the same was as POST/PUT requests -- and should maybe just use the same logic, though I realize that there's specific code in place there for allowing different results based on different encodings.

**Comment by ankitrg** [comment]
I am trying to make `POST` calls to facebook with a hash with lot of nested data:

```ruby
data = {"name"=>"AK - Website Clicks - 1_creative", "instagram_actor_id"=>"1080287752024929", "object_story_spec"=>{"page_id"=>"481114225258265", "link_data"=>{"message"=>"Automated PPC reporting made easy", "image_hash"=>"08909eb36718d8f4ef060124f1c3f45b", "link"=>"https://www.reportgarden.com", "caption"=>nil, "name"=>"PPC Reporting Tool", "description"=>"Signup now and get 10% off on yearly subscription", "call_to_action"=>{"type"=>"SIGN_UP", "value"=>{"link"=>"https://www.reportgarden.com"}}}}}
```

I make the call via `PostMan` with exact same attributes and the request is sucessful, but fails with `restclient`. I think the issue is with the format in which data is parsed. Can I send `json` string in params with restclient?

**Comment by ab** [comment]
For JSON data, you should serialize the payload to a string before sending
it. Rest-client doesn't speak JSON natively.

**Comment by ankitrg** [comment]
@ab I tried multiple different options, I tried encoding the complete hash to json and also encoding the nested hash to json, still I am unable to get the call through. It would really help if you can point me to some example where I can see how nested hash is being handled. Thanks.
