### ISSUE TITLE
RestClient.post with header parameters return 401 unauthorized

### ISSUE THREAD

**Issue by steve21124** [rest-client/rest-client#131]
RestClient.post 'https://api.domain.com/1/files/4242342322.jpg', 
  :name_of_file_param => File.new('/path/to/file/Billie-1.JPG','rb'),
  :content_type => 'image/jpg',:'X-Parse-Application-Id'=>'apkey1',
  :'X-Parse-REST-API-Key'=>'ap2'

this above return unauthorized. I am trying to set a parameters with three headers

curl -X POST \
  -H "X-Parse-Application-Id: APPKEY" \
  -H "X-Parse-REST-API-Key:RestKey" \
  -H "Content-Type: text/plain" \
  -d 'Hello, World!' \
  https://api.parse.com/1/files/hello.txt

**Comment by MrHubble** [comment]
@steve21124 did you figure out how to fix this?
