### ISSUE TITLE
subresources share the options hash with parent resource

### ISSUE THREAD

**Issue by barmintor** [rest-client/rest-client#134]
When a subresource is created with the [ ] method of RestClient::Resource, it uses the same options hash as the parent.  If the subresource is then given a :block_response option, it's propagated to the parent and sibling subresources.  Is this intended? Otherwise, it seems like a simple dup of the options hash would fix it.

**Comment by ab** [comment]
Very belatedly, I think this behavior is somewhat by design, but even if it isn't we may be stuck with it for compatibility. I would caution against using the RestClient::Resource class due to its confusing semantics.
