### ISSUE TITLE
Java7, HTTPs connection and Proxy not working

### ISSUE THREAD

**Issue by dankie** [rest-client/rest-client#153]
Hi,

I try to connect to a server via the restclient library with Java7 (tried versions: java-7-openjdk-amd64, jdk1.7.0_11 and jdk1.7.0_12) and jruby (tried versions: 1.6.8, 1.7.1, 1.7.2). I need to use a proxy to connect the internet. The server I want to contact listens on the SSL port 443.

The code to reproduce is very simple:
```ruby
RestClient.proxy = ENV['https_proxy']
RestClient.post 'https://server.com/path', json_data, { 'Content-type' => 'application/json' }
```

The result looks like:
* Request: #<RestClient::Request:0x73f1f461 @ssl_ca_file=nil, @raw_response=false, @open_timeout=nil, @args={:method=>:post, :url=>"https://abc.def/url.html", :payload=>"{json_data}", :headers=>{"Content-type"=>"application/json"}}, @headers={"Content-type"=>"application/json"}, @tf=nil, @user=nil, @password=nil, @cookies={}, @payload="", @ssl_client_cert=nil, @processed_headers={"Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate", "Content-type"=>"application/json", "Content-Length"=>"412"}, @method=:post, @url="https://abc.def/url.html", @timeout=nil, @verify_ssl=false, @max_redirects=10, @ssl_client_key=nil, @block_response=nil>
* Result: #<Net::HTTPBadRequest 400 Bad Request readbody=true>
* Result.body.inspect: �=���-bU�#b��5�')by�iDz�)�%����2.�&_NKpG�tJ|��Q�Gd��r:�>Fj0r��A�
                                                                          ؞����F���&!��|	�4`���,m�z�3��[��

I think, the en/decryption on any side does not work properly (as I look the result's body).

If I change 
* back to Java 6 OR 
* to not use SSL OR
* to not use a Proxy

everytrhing works fine. But this can only be changed for testing purposes.

Any ideas?

**Comment by ab** [comment]
Feel free to reopen if this is still an issue.
