### ISSUE TITLE
Bring rest-client-fork back into the fold

### ISSUE THREAD

**Issue by L2G** [rest-client/rest-client#159]
In the beginning, the repository at L2G/rest-client-fork (original home here at rest-client/rest-client) was forked because it was not known what archiloque wanted to do with the official project.

Since he's kindly given his blessing to continue the project under @rest-client, any changes and lingering, unresolved issues in the forked project should be merged back into the main project.

**Comment by ab** [comment]
All of the referenced issues are covered in the 2.0.x branch!
