### ISSUE TITLE
Basic HTTP Authentication (base 64 encoded?)

### ISSUE THREAD

**Issue by mm-gmbd** [rest-client/rest-client#182]
Apologies, this is likely to be a quick one. But I note that I can simply set a :user and :password in a request for basic HTTP Authentication -- at what point is this actually base 64 encoded and added as an actual Authentication header? 

After setting the :user and :password I was still getting an unauthorized error in the response, so as a sanity check I decided to print the headers all I got back was a hash that had the :user and :password values I had supplied in the get call. I had expected to see a hash of the actual headers, but what I saw was just a hash that contained the :user and :password keys that I had supplied in the initial call, rather than something like  {:Authorization => "Basic base64encodedstuff"}

**Comment by ab** [comment]
It sounds like you passed `:user` and `:password` in the headers hash rather than as options. Note that the shortcut methods like `RestClient.get` and `RestClient.post` only allow passing headers, and don't support passing options.

Try something like this:

    RestClient::Request.execute(method: :get, url: "http://...", user: 'myuser', password: 'secret', ...)
