### ISSUE TITLE
OPTIONS request no response body

### ISSUE THREAD

**Issue by zanedeg** [rest-client/rest-client#194]
The OPTIONS request method doesn't seem to support a response body, will this be added sometime in the future?

**Comment by ab** [comment]
rest-client does support passing bodies to OPTIONS requests by using `RestClient::Request.execute` or similar.

For example:

```ruby
RestClient::Request.execute(method: :options, url: 'http://example.com', payload: 'some-payload')
```

The top-level class methods like `RestClient.options()` definitely currently have a lousy API, but it'll have to wait for a new major version to refactor them.
