### ISSUE TITLE
Can I use Rest-Client for get HTTP status codes?

### ISSUE THREAD

**Issue by tit** [rest-client/rest-client#196]
I want get 401 status code, but...

    2.0.0-p195 :001 > require 'rest-client'
     => true 
    2.0.0-p195 :002 > request = RestClient.get 'http://SomeServerWithHttpBasicAuthentication.com'
    RestClient::Unauthorized: 401 Unauthorized: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>401 Authorization Required</title>
    </head><body>
    <h1>Authorization Required</h1>
    <p>This server could not verify that you
    are authorized to access the document
    requested.  Either you supplied the wrong
    credentials (e.g., bad password), or your
    browser doesn't understand how to supply
    the credentials required.</p>
    <hr>
    <address>Apache/2.2.21 (Atomic) Server at SomeServerWithHttpBasicAuthentication.com Port 80</address>
    </body></html>    
    from /Users/TIT/.rvm/gems/ruby-2.0.0-p195/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
    from /Users/TIT/.rvm/gems/ruby-2.0.0-p195/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
    from /Users/TIT/.rvm/gems/ruby-2.0.0-p195/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
    from /Users/TIT/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from /Users/TIT/.rvm/gems/ruby-2.0.0-p195/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
    from /Users/TIT/.rvm/gems/ruby-2.0.0-p195/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
    from /Users/TIT/.rvm/gems/ruby-2.0.0-p195/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
    from /Users/TIT/.rvm/gems/ruby-2.0.0-p195/gems/rest-client-1.6.7/lib/restclient.rb:68:in `get'
    from (irb):2
    from /Users/TIT/.rvm/rubies/ruby-2.0.0-p195/bin/irb:16:in `<main>'

**Comment by ab** [comment]
The RestClient API is a little bit quirky here, but if you want the response on an HTTP non-successful status code, you can call `.response` on the exception.

    begin
      RestClient.get('http://example.com/nonexistent')
    rescue RestClient::ExceptionWithResponse => err
      puts err.response
    end

**Comment by lokeshjawane** [comment]
hi @ab 
Is it possible to get response body in rescue section. when i hit below task

a = RestClient::Request.new({:url => "https://xxx.xxx.xxx.xxx:0000/api/aabbcc/v3/vms", :method => :post, :verify_ssl => false, :user => "admin", :password => "xxxxxxxx", :payload => j, :headers => {"Content-type" => "application/octet-stream; charset=UTF-8"}}).execute

Here i'm getting 500 err code in response body
{"state": "ERROR", "code": 500, "message_list": [{"reason": "INTERNAL_ERROR", "message": "Internal Server Error. 'str' object has no attribute 'iterlists'"}], "api_version": "3.1"}

but in api explorer, the resp body somethings else
{
  "state": "ERROR",
  "code": 422,
  "message_list": [
    {
      "message": "Request could not be processed.",
      "reason": "INVALID_REQUEST",
      "details": {
        "spec.resources.disk_list.2.data_source_reference.uuid": [
          "u'ebb76a9-18ec-401b-aaba-a65da8dc2383' does not match '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'"
        ]
      }
    }
  ],
  "api_version": "3.1"
}

So is there any way that i can get the actuall err resp body?
