### ISSUE TITLE
JSON Payload with Array is transformed incorrectly

### ISSUE THREAD

**Issue by mzimen** [rest-client/rest-client#213]
I want to post request with JSON formatted payload. But with following REST request's payload, is returning 422 error message.

 '{"name":"app3","cartridges": [{"url":"https://raw.github.com/jhou1/v2php/master/metadata/manifest.yml"}, {"url":"https://raw.github.com/xltian/mysqlv2newcartridge/master/metadata/manifest.yml"},{"url":"https://raw.github.com/jhou1/v2cron/master/metadata/manifest.yml"}]}' 

The code for initializing request is here:

req = RestClient::Request.new(:url => "#{url}.json", :user => global_options[:login],
                                    :password => global_options[:password],
                                    :method => method, :payload => params,
                                    :headers => {
                                      'Content-Type' => 'application/json',
                                      'Accept' => accept,
                                    },
                                    :timeout => timeout, :open_timeout => timeout)

As the result of initialization, the payload is transformed to the string without the "[":

@payload="name=app3&cartridges[url]=https%3A%2F%2Fraw.github.com%2Fjhou1%2Fdownloadable-php%2Fmaster%2Fmetadata%2Fmanifest.yml&cartridges[url]=https%3A%2F%2Fraw.github.com%2Fjhou1%2Fdownloadable-mysql%2Fmaster%2Fmetadata%2Fmanifest.yml"

from my observation, if there is no JSON array, it works quite well. I assume, that for Hash, we don't want to transform it into UrlEncoded string.

thanks.

**Comment by ab** [comment]
This is extremely belated, but still might be helpful to future users:

Was `params` above a complex object, such as a Hash? RestClient does _not_ automatically serialize your payload into JSON, even if you specify a `Content-Type: application/json`. So if you pass a complex Hash object as the payload, it will try to serialize it as `application/x-www-form-urlencoded`.

You probably want to pass the payload as a String, which will be passed through as is.

    req = RestClient::Request.new(:url => url, :payload => JSON.generate(params), ...)

**Comment by maguri** [comment]
`JSON.generate(params)` works for me!

**Comment by raquelhortab** [comment]
in my case this did not work since the api I was posting to did not expect a json, I had to use this:

```
        headers: {
          'Content-Type' => 'application/x-www-form-urlencoded'
        },
        payload: params.to_query,
```
