### ISSUE TITLE
Character encoding not honored when using Content-Encoding

### ISSUE THREAD

**Issue by plaa** [rest-client/rest-client#224]
We're using rest-client in our functional testing.  We ran into a problem on Windows machines when enabling GZIP compression.

When the server response is not compressed (i.e. no Content-Encoding), then the response body uses the correct encoding defined in the Content-Type header (UTF-8) in both Windows and Linux.  However, if the response is compressed, then the response body uses the default charset instead of that specified by Content-Type.  It works fine in Linux, but fails on Windows.

I checked using a debug proxy that the headers are set correctly.  There's two possible workarounds:
1. Explicitly set 'Accept-Encoding' header empty so the response won't be compressed.
2. Use .force_encoding('UTF-8') to force the response body into the correct charset.

The following are the server response headers:

HTTP/1.1 200 OK
Date: Wed, 28 Aug 2013 08:10:20 GMT
Expires: Fri, 02 Jan 1970 12:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Type: application/json;charset=UTF-8
Connection: close
Server: Jetty(8.1.5.v20120716)

**Comment by ab** [comment]
I think this should be fixed in master.
