### ISSUE TITLE
Implementation of exceptions is inconsistent with documentation

### ISSUE THREAD

**Issue by laskaridis** [rest-client/rest-client#229]
In the documentation of RestClient::Exception it is mentioned:

  # This is the base RestClient exception class. Rescue it if you want to
  # catch any exception that your request might raise
  # You can get the status code by e.http_code, or see anything about the
  # response via e.response.
  # For example, the entire result body (which is
  # probably an HTML error page) is e.response.

However in 1.6.7 version a RestClient::BadRequest exception is thrown on 400 responses which does not extend RestClient::Exception.

**Comment by ab** [comment]
The exceptions are definitely not very consistent. But even in 1.6.7 `RestClient::BadRequest` does inherit from `RestClient::Exception`.

**Comment by ab** [comment]
This is mostly better on master now.
