### ISSUE TITLE
rest-client uses system proxy even though RestClient.proxy is set to nil

### ISSUE THREAD

**Issue by trondbert** [rest-client/rest-client#230]
Hi!

We encountered a problem in ruby-2.0.0p195. Requests made by rest-client used the system's underlying proxy (in this case the environment variable http_proxy on Unix/Linux/Mac) even though RestClient.proxy was set to nil. We believe this is due to a change in net/http in ruby 2.

We forked rest-client and we have a fix here: https://github.com/bring/kp-rest-client/commit/cc872eb643e57e6ee13c0533c0c55f545ed0e4b1

Please consider pulling this commit into rest-client :)

Best Regards
Trond Valen

**Comment by darrenleeweber** [comment]
The current implementation does not seem to use the system proxy value, at least after require; i.e.

```
$ pry
[1] pry(main)> require 'rest-client'
=> true
[2] pry(main)> RestClient.proxy
=> nil
[3] pry(main)> ENV['http_proxy']
=> "http://proxy.example.org:80"
```

That is, the RestClient.proxy value is not representing whether the system proxy is used or not.  However, when a request is sent, the system proxy may be used; e.g.

```
[4] pry(main)> response = RestClient.get 'http://www.google.com';
[5] pry(main)> response.code
=> 200
```

**Comment by ab** [comment]
Fixed by https://github.com/rest-client/rest-client/pull/383
