### ISSUE TITLE
HTTP 404 is "Resource Not Found" rather than "Not Found" per RFC

### ISSUE THREAD

**Issue by ab** [rest-client/rest-client#265]
In RFC 2616, the 404 status code is described as "Not Found", whereas it's rendered as "Resource Not Found" and `RestClient::ResourceNotFound` in rest-client. I'm not sure this is worth fixing, but it does seem to be a wart. There will of course be backwards-compatibility concerns with any change.

https://tools.ietf.org/html/rfc2616#section-10.4.5
https://en.wikipedia.org/wiki/HTTP_404
http://httpstatus.es/404

**Comment by ioquatix** [comment]
@ab I thin you shouldn't inherit from `Exception` but rather `StandardError`?

**Comment by ab** [comment]
Right, that's `RestClient::Exception`, not ` ::Exception`.

**Comment by ioquatix** [comment]
@ab Ah yep, sorry wasn't clear. Perhaps the root should be HTTPError or something more descriptive?

**Comment by ab** [comment]
Fixed in https://github.com/rest-client/rest-client/pull/382
