### ISSUE TITLE
Difference between RestClient::RequestTimeout and Errno::ETIMEDOUT

### ISSUE THREAD

**Issue by ghost** [rest-client/rest-client#272]
I'm trying to rescue some exceptions and I was wondering what the difference is between RestClient::RequestTimeout and Errno::ETIMEDOUT or Timeout::Error?

**Comment by ankitrg** [comment]
I was facing the problem of how to rescue the `SocketError`, instead we should rescue `Errno::ETIMEDOUT`
http://stackoverflow.com/questions/40779163/how-to-rescue-socket-error-in-ruby?noredirect=1#comment68782556_40779163
