### ISSUE TITLE
RestClient::SSLCertificateNotVerified certificate verify failed, How can we bypass

### ISSUE THREAD

**Issue by kamal2222ahmed** [rest-client/rest-client#288]
After install rest-client on CentOs 6.4 VM:

$restclient
/home/kahmed/qa/RESTtestframework/rest-client/rest-client.gemspec:14: warning: Insecure world writable dir /usr/local/rvm/gems/ruby-2.1.1/bin in PATH, mode 042777
2.1.1 :001 > RestClient.get 'https://vm-kahmed.his.vm/administrator'
RestClient::SSLCertificateNotVerified: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed: 
    from /home/kahmed/qa/RESTtestframework/rest-client/lib/restclient/request.rb:440:in `rescue in transmit'
    from /home/kahmed/qa/RESTtestframework/rest-client/lib/restclient/request.rb:345:in`transmit'
    from /home/kahmed/qa/RESTtestframework/rest-client/lib/restclient/request.rb:176:in `execute'
    from /home/kahmed/qa/RESTtestframework/rest-client/lib/restclient/request.rb:41:in`execute'
    from /home/kahmed/qa/RESTtestframework/rest-client/lib/restclient.rb:64:in `get'
    from (irb):1
    from /home/kahmed/qa/RESTtestframework/rest-client/bin/restclient:92:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/restclient:23:in `load'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/restclient:23:in`<main>'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in`<main>'

Is there a way to bypass, or accept the Cert ?

**Comment by mrjcleaver** [comment]
> If you're going to use SSL you may as well verify the certificate, otherwise you're not really getting any protection from it.

True, unless you happen to be on a demo system with a self-signed certificate.

Thanks for question and the hint how to fix!

**Comment by ajsharp** [comment]
I only have this problem with this problem with RestClient in development, but not with any other http clients.

**Comment by ab** [comment]
Probably most HTTP clients don't verify certificates by default. What CA is the certificate in question signed by?

**Comment by dvmarcilio** [comment]
I had the same issue using `:ssl_ca_file => "myca.crt"`. Then I did some digging and found out that the .crt was encoded as a binary DER.
 Converting to .pem was the solution: `openssl x509 -inform DER -outform PEM -in myca.crt -out myca.crt.pem`

**Comment by ajsharp** [comment]
@ab I think it used to be the case that most http clients don't verify the certs by default, by I don't believe that to be the case anymore. Of course, I could be wrong, I'm speculating on that.

Is it necessary to manually set the `ssl_ca_file`? Does it default to something? Thanks.

**Comment by ab** [comment]
It should not be necessary to set `ssl_ca_file`. By default, rest-client will use the system default certificate store via `OpenSSL::X509::Store#set_default_paths`.

There are three ways to specify CA information:
- `:ssl_ca_file`
- `:ssl_ca_path`
- `:ssl_cert_store`

**Comment by nburt** [comment]
I'm currently trying to upgrade from 1.6.7 -> 1.8.0 and running into this error. The weird thing is that as far as I can tell, it only occurs when I make a request to Google domains.

In the rails console after upgrading:
```ruby
# Works
RestClient.get("https://vimeo.com")
RestClient.get("https://www.verbalizeit.com")
RestClient.get("https://www.nytimes.com")
RestClient.get("https://www.facebook.com")
RestClient.get("https://www.twitter.com")
RestClient.get("https://www.linkedin.com")

# Raises RestClient::SSLCertificateNotVerified
RestClient.get("https://www.youtube.com")
RestClient.get("https://www.google.com")
RestClient.get("https://abc.xyz/")
```
My coworker is able to run the same code without issue so I assume it must have something to do with my machine.

Does anyone have any ideas on how to debug?

**Comment by ab** [comment]
@nburt What platform and Ruby version is this on?

Can you try `https://www.name.com`? It also uses the same root CA as Google (GeoTrust Global CA), though with a different intermediate.

**Comment by nburt** [comment]
@ab I'm using Rails 4.2.5 (same issue on 4.2.4) and Ruby 2.2.3.

`https://www.name.com` works for me

**Comment by ab** [comment]
@nburt What OS version?

**Comment by nburt** [comment]
@ab OSX 10.11 El Capitan

**Comment by ab** [comment]
If you look in your keychain do you see any CA entries for `Google Internet Authority G2`? You might also be able to test behavior using `openssl s_client -connect google.com:443`.

OpenSSL on OS X is a bit of a mess, since Apple monkey patches it to always fall back on the system keychain CAs even if you specify a specific CA file or directory.

**Comment by nburt** [comment]
I don't see any entries for Google Internet Authority G2. What should I be looking for when running the openssl command? 

Thanks!

**Comment by ab** [comment]
You're looking for the `Verify return code` part. Here I use a `-CApath /etc/ssl/certs/` because this is on a Linux machine, which shouldn't be relevant for OS X:

```
$ openssl s_client -connect google.com:443 -CApath /etc/ssl/certs/
CONNECTED(00000003)
depth=3 C = US, O = Equifax, OU = Equifax Secure Certificate Authority
verify return:1
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify return:1
depth=1 C = US, O = Google Inc, CN = Google Internet Authority G2
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google Inc, CN = *.google.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.google.com
   i:/C=US/O=Google Inc/CN=Google Internet Authority G2
 1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
---
[snip]
...
    Verify return code: 0 (ok)
```

**Comment by nburt** [comment]
Oh ok, yeah I do get the "Verify return code: 0 (ok)" when I run it

**Comment by ab** [comment]
Hmm, that's surprising. What happens when you verify SSL certificates using the older rest-client 1.6.x release? e.g. `RestClient::Request.execute(method: :get, url: 'https://www.google.com', verify_ssl: true)`

**Comment by nburt** [comment]
I get the following error:

```ruby
Loading development environment (Rails 4.2.4)
2.2.3 :001 > RestClient::Request.execute(method: :get, url: 'https://www.google.com', verify_ssl: true)
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /Users/nathanaelburt/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/nathanaelburt/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/nathanaelburt/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/nathanaelburt/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/nathanaelburt/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/nathanaelburt/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
	from (irb):1
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/nathanaelburt/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
```

**Comment by ab** [comment]
Does this also happen using system ruby? I wonder if this is an RVM + OS X thing:

https://rvm.io/support/fixing-broken-ssl-certificates
https://github.com/rvm/rvm/blob/master/help/osx-ssl-certs.md

**Comment by nburt** [comment]
It works using system ruby.

I had tried those RVM fixes yesterday but they didn't work. I get that they're all up to date when I run it:

```ruby
○ → rvm osx-ssl-certs update all
Updating certificates for /usr/local/etc/openssl/cert.pem: Already up to date.
Updating certificates for /etc/openssl/cert.pem: Already up to date.
Updating certificates for /etc/openssl/cert.pem: Already up to date.
```

**Comment by ab** [comment]
OK this is way deeper into OS X / RVM than I'm familiar with. (I don't have a machine handy to be able to test this.) Doesn't seem like it's related to rest-client, in any case. Sorry to not be able to narrow it down further.

**Comment by nburt** [comment]
Ok, no problem. I appreciate all your help. I'll post here if I'm able to resolve it.

**Comment by gtmax** [comment]
http://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html solved it for me (rvm reinstall my-ruby-version --disable-binary).

**Comment by dannyxu2015** [comment]
@gtmax the link [changed](https://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html)

**Comment by saiatwork19** [comment]
HI i am using rest-client 1.7.3, when i dnt pass ssl_ca_file i am getting success full response. if i pass it i am getting "SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed" .

i verified the certificate what i am passing using "openssl s_client -connect xxxx:443

can you please suggest me...

**Comment by balogic** [comment]
At what location do we need to place the `.pem` file? , inorder to mention it in `:ssl_ca_file => "myca.crt.pem"`

**Comment by ab** [comment]
@balogic These paths work the same way as any old path in Ruby, like with a
`File.open`. It can be a path relative to your current directory or an
absolute path.

On Feb 27, 2017 2:08 AM, "Balaji Ravichandran" <notifications@github.com>
wrote:

At what location do we need to place the .pem file? , inorder to mention it
in :ssl_ca_file => "myca.crt.pem"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rest-client/rest-client/issues/288#issuecomment-282644066>,
or mute the thread
