### ISSUE TITLE
How to pass verify_ssl to RestClient.get/put/delete

### ISSUE THREAD

**Issue by net1957** [rest-client/rest-client#297]
I use many  RestClient.get/put/delete methods in my application and due to internal issue I need to set verify_ssl to false.

ex:

```
RestClient.get("#{@host}/#{service}", user_agent: CFG.webservice.user_agent, verify_ssl: false)
```

but that seems to be passed in headers... as the doc say!
Should I use RestClient::Request ? Seems to be a big change...

**Comment by hayesgm** [comment]
Thanks for this. I see this popping up now and then in some issues. While I understand that `verify_ssl: false` is not something we'd like to actively promote, it may be worthwhile making how to do this more clear.
