### ISSUE TITLE
Don't set SSL options unless we have an HTTPS URI

### ISSUE THREAD

**Issue by ab** [rest-client/rest-client#302]
This is probably going to require a refactor of `RestClient::Request.transmit`, which currently receives a `uri` argument. SSL options are set up in various ways in `initialize`, where we don't yet know whether we have an HTTPS URI.

It seems like `transmit` should actually be private, but this could possibly be a breaking change, and will require rewriting some tests.

**Comment by mamantoha** [comment]
:+1: We have this issue too only with JRuby(1.7.18) on Windows.
Moved to rest-client 1.6.8 and it works fine.

**Comment by mamantoha** [comment]
It's works with `JRuby 9.0.0.0.pre2` and `rest-client 1.8.0` :smile_cat:
