### ISSUE TITLE
When passing a params hash, params are being compressed

### ISSUE THREAD

**Issue by mcsoup** [rest-client/rest-client#303]
When I try to pass a params hash via POST the params are compressed. Not normally a problem except when dealing with nested_attributes of strong parameters.

Example:
params = {foo:{label: 'Foo', bar_attributes:[{label: 'Bar'}]}}
becomes
params = {foo:{label: 'Foo', bar_attributes:{label: 'Bar'}}}
when the square brackets are removed

**Comment by ab** [comment]
What would the desired behavior here be? In general, if you have special complicated behavior, I'd recommend building the URL yourself rather than using the params hash.

Feel free to reopen with more information here.

**Comment by jlhonora** [comment]
I second this. Almost lost it trying to find the cause for this "bug" :) .

The problem is that if the value is an array with a single element, then the value is transformed to a hash. The desired behavior (at least for my use case) would be to leave the parameters just like that, `bar_attributes:[{label: 'Bar'}]`.

A simple workaround is to use `payload: params.to_json` and add `Content-Type: application/json` to your headers hash.

The params "compression" could be optional, and I think it is better for it to be disabled by default. If it makes sense then I can take a look and see if I can make a PR.

**Comment by ab** [comment]
@jlhonora Can you describe what you'd like to see on the wire?

For example, here's one possible interpretation, which is what the code in #437 does right now:

```
>> x = {foo: {label: 'Foo', bar_attributes:[{label: 'Bar'}]}}

>> RestClient::Utils.flatten_params(x)
=> [["foo[label]", "Foo"], ["foo[bar_attributes][][label]", "Bar"]]

>> RestClient::Utils.encode_query_string(x)
=> "foo[label]=Foo&foo[bar_attributes][][label]=Bar"
```

**Comment by jlhonora** [comment]
Taking your same `x` parameter example, what I'd like to see whenever I make a GET or POST request with the payload as a JSON body, is to have the same payload on the other end.

So, over the wire, it should look just like `x.to_json`, i.e.: `{"foo":{"label":"Foo","bar_attributes":[{"label":"Bar"}]}}`

Anyhow, if you take the specific use case of transforming parameters for URI building, the "correct" output is somehow ambiguous (diving into RFCs right now, I'll let you know if I find something more specific). I've seen two ways to do param encoding, with `URI.encode_www_form` and with ActiveSupport's `Object.to_param` method ([ref1](http://ruby-doc.org/stdlib-2.0.0/libdoc/uri/rdoc/URI.html#method-c-encode_www_form) [ref2](http://api.rubyonrails.org/classes/Object.html#method-i-to_param)).

`URI.encode_www_form` does flatten arrays, but doesn't seem to handle nested hashes well enough:

```
> puts CGI.unescape(URI.encode_www_form("q" => [{"ruby" => "perl"}], "lang" => "en"))
q={"ruby"=>"perl"}&lang=en
> puts CGI.unescape(URI.encode_www_form("q" => {"ruby" => "perl"}, "lang" => "en")) # Notice missing brackets
q={"ruby"=>"perl"}&lang=en
```

ActiveSupport's `Object.to_query` does handle arrays and nested hashes, but the parameters are sorted alphabetically (I don't know if that's a pain point, shouldn't be I guess?):

```
> x = {foo: {label: 'Foo', bar_attributes:[{label: 'Bar'}]}}
> puts CGI.unescape(x.to_param)
foo[bar_attributes][][label]=Bar&foo[label]=Foo
> x = {foo: {label: 'Foo', bar_attributes:{label: 'Bar'}}}
{:foo=>{:label=>"Foo", :bar_attributes=>{:label=>"Bar"}}}
> puts CGI.unescape(x.to_param)
foo[bar_attributes][label]=Bar&foo[label]=Foo
```
which is slightly different from the current output of `RestClient::Utils.encode_query_string(x)`.
