### ISSUE TITLE
RestClient post is not working with nested json?

### ISSUE THREAD

**Issue by kahou82** [rest-client/rest-client#309]
I have a nested json looks like this:

test["type"] = {"animal"=> [{"item1" => "1234", "item2" => "2345", "item3"=> "1357"},
                                       {"item1" => "2345", "item2"=> "1234", "item3"=> "2468"}]}

If I post it with as_json:

RestClient.post(url, test.as_json, headers)

The array got stripped out. 

Is it a known issue?

**Comment by ab** [comment]
Feel free to reopen with more detail here.
