### ISSUE TITLE
Redirect for POST request does not work

### ISSUE THREAD

**Issue by ramasrin** [rest-client/rest-client#312]
I am trying to invoke POST request for a REST API. logging is enabled. From the console, i could see that addInfo is invoked, redirection happens to login page. The login page request is successful, but actual addInfo is not invoked. Not sure, what is the issue. I am using Ruby 1.9.3

RestClient.post("#{host}/addInfo", request_body_map.to_json,  {:authorization => "Basic #{Base64.strict_encode64("#{user}:#{pwd}")}", :accept => 'application/json',:content_type => 'application/json', :timeout => 30} ) { |response, request, result, &block|
  if [301, 302, 307].include? response.code
    puts "error code :302"
    response.follow_redirection(request, result, &block)
  else
    response.return!(request, result, &block)
  end
}

**Comment by ab** [comment]
Going to close this out, but feel free to reopen.

**Comment by ramasrin** [comment]
ok fine.
with regards,
Srinivasan R
