### ISSUE TITLE
Limit DNS resolution to IPv4

### ISSUE THREAD

**Issue by janpieper** [rest-client/rest-client#331]
If we use RestClient or cURL to send a GET request to one of our hosts, it is really slow:

```
$ time curl <host>
[...]
real    0m5.531s
user    0m0.000s
sys     0m0.006s
```

``` ruby
s = Time.now
RestClient.get("<host>")
puts Time.now - s # 5.627323704
```

We found out that the requests are much faster if we only use IPv4 to resolve the DNS:

```
$ time curl -4 <host>
[...]
real    0m0.017s
user    0m0.005s
sys     0m0.000s
```

```
-4, --ipv4
       If curl is capable of resolving an address to multiple  IP  ver‐
       sions  (which  it  is  if it is IPv6-capable), this option tells
       curl to resolve names to IPv4 addresses only.
```

Is there a way to do this with RestClient?

**Comment by akostadinov** [comment]
Was this DNS resolution issue or IP protocol version routing issue? I wonder if one bright day in the future ruby will get proper IPv6 fallback support https://bugs.ruby-lang.org/issues/17525
