### ISSUE TITLE
Authentication by token

### ISSUE THREAD

**Issue by viniciusalonso** [rest-client/rest-client#339]
Good Afternoon guys,
How i pass  a token like a http protocol param ?

I need pass a token for authorization in api.
I am using the code below.

```ruby
require 'rest-client'
RestClient.post('http://api.example.com/search/query', params: { token: 'a2m...' })
```
For example,I do it using curl

```console
 curl -X POST http://api.example.com/search/query -H 'Authorization: Token token=a2m...'
```

Thanks in advance :)

**Comment by ab** [comment]
The RestClient.post helper requires three arguments to pass headers like that: `.post(url, params, headers)`. Have you tried something more like this?

    RestClient.post('http://api.example.com/', {key: 'value'}, authorization: 'a2m...')

This will result in headers like this:

    Accept: */*; q=0.5, application/xml
    Accept-Encoding: gzip, deflate
    Authorization: a2m...

**Comment by MrHubble** [comment]
@ab when I try  your suggestion I get `RestClient::Unauthorized - 401 Unauthorized`.

As far as I can tell my implementation is the same as yours:
`RestClient.post "http://api.example-dev.com:7000/v1/resource", {key: 'value'}, :authorization => 'token..'`

**Comment by MrHubble** [comment]
From what I can tell the main order of things when I call `post` will be:

````rb
#restclient.rb
  def self.post(url, payload, headers={}, &block)
    Request.execute(:method => :post, :url => url, :payload => payload, :headers => headers, &block)
  end
````

````rb
#request.rb

    def execute & block
      uri = parse_url_with_auth(url)
      ....

    end

   def parse_url_with_auth(url)
      uri = parse_url(url)
      @user = CGI.unescape(uri.user) if uri.user
      @password = CGI.unescape(uri.password) if uri.password
      if !@user && !@password
        @user, @password = Netrc.read[uri.hostname]
      end
      uri
    end
````

So I think an unauthorized may be thrown because of `Netrc.read[uri.hostname]` ?

**Comment by ab** [comment]
@MrHubble I think you're talking about #374, which is fixed on master. If there's sufficient interest I might backport it to 1.8.x.

**Comment by MrHubble** [comment]
@ab thank you for taking the time to reply. My problem was that I didn't realise I needed to include `Token token=` with my authorization token. Adding that fixed my issue.

````rb
`RestClient.post "http://api.example-dev.com:7000/v1/resources", {:test => {key: '1234'}}, :authorization => 'Token token=yyyyyyyyyyyyyy'`
````

**Comment by Formless** [comment]
Backporting it would be appreciated @ab  if it's not already
