### ISSUE TITLE
DELETE with Payload

### ISSUE THREAD

**Issue by gumatias** [rest-client/rest-client#341]
Please correct me if I'm wrong but from what I've seen [1], passing a payload when performing a DELETE is not supported. Is this correct or are there other options?

i.e. https://developer.spotify.com/web-api/remove-tracks-playlist/

Thanks!

[1] https://github.com/rest-client/rest-client/blob/master/lib/restclient.rb#L80

**Comment by ab** [comment]
Hi there,

The top level helpers like `RestClient.delete` are pretty inflexible, and unfortunately we can't fix them without seriously breaking backwards compatibility. But they're just very thin wrappers over `.execute`.

I'd recommend doing something like this:

    RestClient::Request.execute(:method => :delete, :url => url, :payload => payload)

**Comment by gumatias** [comment]
Thanks for the response!

I don't mean to be annoying, but do you mind explaining why adding an overloaded version of the ['delete'][1] function wouldn't be a good idea? e.g.:

    def self.delete(url, payload, headers={}, &block)
        Request.execute(:method => :delete, :url => url, :payload => payload, :headers => headers, &block)
    end

Thank you!

[1]: https://github.com/rest-client/rest-client/blob/master/lib/restclient.rb#L80

**Comment by gumatias** [comment]
[NVM my previous question][1]
[1]: http://stackoverflow.com/questions/9373104/why-doesnt-ruby-support-method-overloading

**Comment by ab** [comment]
Right, this would break compatibility with prior callers that expect the last argument to be the headers hash. It's a really unfortunate API design that led us to be in this place.
