### ISSUE TITLE
`request.payload` return "" inside `RestClient::Request.execute` block

### ISSUE THREAD

**Issue by filipebarcos** [rest-client/rest-client#357]
Hi all,

I'm having a small problem with RestClient, where I'm trying to access `request.payload` when using the `execute` method. What I'm trying to do is:

``` ruby
RestClient::Request.execute({
  url: 'http://myurl.com/with/path', 
  user: 'myuser', 
  password: 'mypassword', 
  method: :post, 
  payload: {id: 1, description: 'description'}.to_json,
}) do |response, request, result, &block|
  puts request.payload.inspect # => ""
  puts request.args[:payload].inspect # => "\"[{\\\"id\\\":\\\"1\\\",\\\"description\\\":\\\"description\\\"}]\""
end
```

I just want to make sure I'm not doing anything wrong, or is there another issue open for this, or is a expected behaviour...

Can someone help me here? I can work on a fix for this, if it's the case.

UPDATE: I'm being able to make successful request, I just want a better way to access payload from that `request` object.

**Comment by sai43** [comment]
just try like this....!

         url      =  'url-path' 
        payload  =  { :latitude => latitude, :longitude => longitude, :moods => @mood.split(","), :eventStartWindow => @event_start_date, :eventEndWindow => @event_end_date }
        payload  =   payload.to_json
        Rails.logger.info "Payload: #{payload}"

        response = RestClient::Request.execute(
        :method => :post,
        :url => url,
        :content_type => :json,
        :payload => payload
        )

       Rails.logger.info "Response Code: #{response.code}"
      @search_events = JSON.parse(response)

**Comment by filipebarcos** [comment]
that way I'm not able to get error handling properly. Passing a block to `RestClient::Request.execute`, I can have special treatment for certain status responses. Like shown here: https://github.com/rest-client/rest-client#response-callbacks

**Comment by scytherswings** [comment]
I'd like to chime in that this is affecting me as well. I have created my own error handler and log formatter which uses request.payload so that I can generalize and only log the payload when there is an error. I can make a workaround, but using the request from the block is much cleaner if it could contain the payload.

```ruby
  def cookie_auth(user, method, url, headers, payload, executed = false)
    if user.cookie.nil?
      return basic_auth(user, method, url, headers, payload)
    end
    head = headers.dup
    logger.info("Using Cookie Auth")
    logger.debug("Cookie looks like: #{user.cookie}")
    cookie = JSON.parse(user.cookie)
    RestClient::Request.execute method: method, url: url,
      headers: headers, payload: payload,
      cookies: cookie do |resp, request, result, &block|

      case resp.code
        when 200..202
          logger.info("20X from blank.")
          log_request_data(user: user, request: request, response: resp, log_level: Logger::INFO, clear_cookie: false)
          parsed = (JSON.parse(resp))
          if parsed.length > 0
            logger.debug("The response body has a length of: #{parsed.length}")
            return parsed
          else
            logger.warn("Got empty response from blank, clearing cookie just in case")
            user.update!(:cookie => nil)
            return parsed
          end
        when 400, 401
          logger.warn("Cookie was bad, authenticating")
          logger.warn("Resetting headers to remove bad cookie")
          log_request_data(user: user, request: request, response: resp)
          return basic_auth(user, method, url, head, payload)
        when 404
          logger.warn("Got 404 Not Found from blank")
          log_request_data(user: user, request: request, response: resp)
          if !executed
            logger.warn("Sleeping for 500ms and trying again")
            sleep(0.5)
            cookie_auth(user, method, url, headers, payload, true)
          else
            logger.warn("API query-retry failed after waiting 500ms.")
          end
          raise SumoAPIException.new "404 Bad Request", resp
        when 500
          logger.warn("Got 500 back from blank")
          log_request_data(user: user, request: request, response: resp)
          logger.warn("Going to be optimistic and try normal auth")
          return basic_auth(user, method, url, head, payload)
      end
    end
  end


  def log_request_data(user:, request:, response:, log_level: Logger::WARN, clear_cookie: true)
    raise TypeError unless request.is_a? RestClient::Request

    logger.add(log_level){"Request and response data below..."}
    logger.add(log_level){"Request method: #{request.method.upcase}"}
    
    #this should return the payload, but it is always ""
    if !request.payload.nil?
      logger.add(log_level){"Request Payload: #{request.payload}"}
    end
    logger.add(log_level){"Headers: #{request.headers}"}
    logger.add(log_level){"Cookies: #{request.cookies}"}
    logger.add(log_level){"URL: #{request.url}"}
    
    if log_level == Logger::DEBUG || log_level > Logger::WARN
      logger.add(log_level){"Response: #{response}"}
    end
    
    if response.is_a? RestClient::Response
      logger.add(log_level){"Response cookies: #{response.cookies}"}
    end
    
    if clear_cookie
      user.update!(:cookie => nil)
    end
  end
```

Thanks for creating this gem, I use it in all of my projects!

**Comment by scytherswings** [comment]
Also, as far as my code is concerned, "cleaner" is a relative term. lol

**Comment by helperton** [comment]
@scytherswings I see your comment: "#this should return the payload, but it is always """, this is happening to me too.  Is it a bug in .execute?

**Comment by scytherswings** [comment]
@helperton Oh man, it has been a long time since I've looked at this.. I believe it was but I have since stopped using the code I wrote so long ago so I can't say whether it is still happening.

**Comment by filipebarcos** [comment]
Not sure if this is still a concern or not. Haven't used it since the time I opened this issue. I'm closing this, and in case someone is affected by it again, recently (maybe you @helperton), I suggest to open another issue. Feel free to reference this one, but I think this one does not make sense to be opened any longer, it's just bloat to this gem backlog.
