### ISSUE TITLE
confusing error on negative string size (or size too big) (ArgumentError) on large (1.9 GB) response

### ISSUE THREAD

**Issue by matkoniecz** [rest-client/rest-client#359]
```
require 'rest-client'
url = 'http://overpass-api.de/api/interpreter?data=[timeout:3600];(node(51.8455934,4.8238493,52.3455934,5.3238493);%3C;);out%20meta;'
RestClient::Request.execute(:method => :get, :url => url, :timeout => 3600)
```

results in

```
/home/mateusz/.gem/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:504:in `read': negative string size (or size too big) (ArgumentError)
    from /home/mateusz/.gem/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:504:in `decode'
    from /home/mateusz/.gem/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:489:in `process_result'
    from /home/mateusz/.gem/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:421:in `block in transmit'
    from /usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /home/mateusz/.gem/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit'
    from /home/mateusz/.gem/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
    from /home/mateusz/.gem/ruby/1.9.1/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
```

Firefox 36 is retrieving this data without problems.

**Comment by ab** [comment]
Are you able to reproduce this with a more minimal test case? I assume this has something to do with the GZip encoding, but I wasn't able to reproduce a problem with a test 5 GB gzipped response.

**Comment by matkoniecz** [comment]
> Are you able to reproduce this with a more minimal test case?

Unfortunately I have no idea how to even start with that one (one of things that may be done is to set up service that will return this response, but I have no idea how it may be done properly).

> test 5 GB gzipped response

Have you tried with OSM data, like this from this case? Maybe it happens because OSM is in XML that is easily compressed (56 GB uncompressed, 4GB compressed would be nothing weird) [note, that is just a wild guess].

**Comment by saiqulhaq** [comment]
@matkoniecz can you give me the URL to test? to reproduce this issue

**Comment by matkoniecz** [comment]
The URL is in the initial report - see 

>  url = 'http://overpass-api.de/api/interpreter?data=[timeout:3600];(node(51.8455934,4.8238493,52.3455934,5.3238493);%3C;);out%20meta;'

**Comment by saiqulhaq** [comment]
Hi @matkoniecz 
I just tried reproduce this issue, and getting error too  

I believe that it's because we are trying to download and save the whole file into memory until download process is complete   

```ruby
require 'rest-client'
url = 'http://overpass-api.de/api/interpreter?data=[timeout:3600];(node(51.8455934,4.8238493,52.3455934,5.3238493);%3C;);out%20meta;'
RestClient::Request.execute(:method => :get, :url => url, :timeout => 3600)
```

I just looked your complete code also in [here](https://github.com/matkoniecz/CartoCSSHelper/blob/110bd2ed8e9b96fedb8cc3e9e173028f7ced4765/downloader.rb)

so I think you should download the file into chunks instead, like this:

```ruby
File.open('/tmp/foo.iso', 'w') {|f|
    block = proc { |response|
      response.read_body do |chunk|
        puts "Working on response" 
        f.write chunk
      end
    }
    RestClient::Request.new(method: :get, url: 'http://mirror.pnl.gov/releases/xenial/ubuntu-16.04-server-amd64.iso', block_response: block).execute
}
```

reference: https://github.com/rest-client/rest-client/issues/452

**Comment by matkoniecz** [comment]
Thanks, I am now testing modified version

```
require 'rest-client'
File.open('test', 'w') {|f|
    block = proc { |response|
      response.read_body do |chunk|
        puts "Working on response" 
        f.write chunk
      end
    }
    RestClient::Request.new(method: :get, url: 'http://overpass-api.de/api/interpreter?data=[timeout:3600];(node(51.8455934,4.8238493,52.3455934,5.3238493);%3C;);out%20meta;', block_response: block).execute
}
```

**Comment by matkoniecz** [comment]
Still I think that either rest-client should support larger responses without manual chunking or give less confusing message ("response too large to be processed in one chunk by rest-client"?).

**Comment by ab** [comment]
I was never able to reproduce this, but feel free to reopen with more information.

**Comment by matkoniecz** [comment]
> I was never able to reproduce this

What is your OS? Maybe it is Linux-only bug.
