### ISSUE TITLE
Response cookies character '+' replace by blank

### ISSUE THREAD

**Issue by crosspass** [rest-client/rest-client#364]
1. Respoonse cookies don't need CGI::escape()
2. when cancel CGI::escape() int the function parse_cookie, then the cookie content character '+' replace by blank
![image](https://cloud.githubusercontent.com/assets/5187746/6702549/44635f3c-cd68-11e4-8192-014e004bddd6.png)

**Comment by ab** [comment]
Is this still relevant in rest-client 1.8.0, which revamps cookie parsing?

**Comment by ab** [comment]
Feel free to reopen with more information.
