### ISSUE TITLE
Rest-Client gem on 1.6-legacy branch is not properly published

### ISSUE THREAD

**Issue by hkraji** [rest-client/rest-client#373]
Watching the current state of branch *1.6-legacy* I've noticed that *rdoc* gem is added as development dependency (as it should be). But current `rest-client (1.6.8)` on *rubygems* is not up to date with current code.

On rubygem's `rest-client` gem has *rdoc gem* as a dependency (non-development) and as such is bringing few not necessary gems with it. 

https://github.com/rest-client/rest-client/blob/v1.6.8/rest-client.gemspec

*rdoc gem* will install *json gem* which will fail without ruby dev on system.

Could you please publish `rest-client` in version `1.6.9`, with this fix in mind. Thank you.

**Comment by knightq** [comment]
+1

**Comment by ab** [comment]
This should be fixed by rest-client 1.6.9 released on June 10.
