### ISSUE TITLE
How can I request in multi session?

### ISSUE THREAD

**Issue by lufeihaidao** [rest-client/rest-client#387]
For example,

```ruby
  threads = ids.map do |id|
    Thread.new do
      RestClient.post get_url(id)
    end
  end
```

I want to send posts in different sessions, is it possible?

**Comment by ab** [comment]
Sorry, what specifically are you trying to do?

**Comment by ab** [comment]
Feel free to reopen with more information.

**Comment by lufeihaidao** [comment]
Sorry I forgot this.

It's like requests in python: http://docs.python-requests.org/en/master/user/advanced/#session-objects

If I created multiple threads, reqs in different thread act like in different browsers.

**Comment by tranngocsam** [comment]
@lufeihaidao Did you resolve this issue? I'm having a similar issue

**Comment by lufeihaidao** [comment]
@tranngocsam Not yet. It seems rest client doesn't provide this solution.

**Comment by tranngocsam** [comment]
@lufeihaidao Thank you. Do you know any gems, libs that provide this solution? I tried with net/http, typhoeus, httparty, but haven't got any lucks yet.
