### ISSUE TITLE
Enhancement request: response.full_uri

### ISSUE THREAD

**Issue by tsunami719** [rest-client/rest-client#388]
For debugging purposes, it would be handy if the response object could tell me how the parameters were added to the base uri.  headers does not seem to supply this information.

**Comment by ab** [comment]
Possibly you want `response.request.url`?

**Comment by tsunami719** [comment]
Yeah thanks that was exactly what I was looking for.  :) 

Perhaps it could be documented a little better?  I missed the request object completely in the README doc. :) And the wiki doesn't seem to have anything.

But feel free to close this, if you don't want to track that.

**Comment by tsunami719** [comment]
Never mind.  I found the documentation at RubyDocs.info
http://www.rubydoc.info/gems/rest-client
