### ISSUE TITLE
Enhancement request: multiple uses of same query key

### ISSUE THREAD

**Issue by michael-reeves** [rest-client/rest-client#389]
I've been playing around with Google's Static Map API.  They allow you to reuse the markers key multiple times, to place multiple pins on a map.  Using the params hash I had to pass this in to make it work.
{ :size => '500x350',
  :scale => 9,
  :markers => 'color:green|100+Wall+St,New+York,NY&markers=color:blue|100+Main+St,Queens,NY' } 

Would it be possible to build the hash using an array for multiple values on the same key?
:markers => ['color:green|100+Wall+St,New+York,NY', 'color:blue|100+Main+St,Queens,NY']

If this is what is being explained in the README, when discussing nested items, then it is not clear, and could be cleaned up.

**Comment by ab** [comment]
There isn't really any standard describing how this behavior should work. But this method for dealing with arrays isn't compatible with the way that rest-client currently deals with params.

I'd recommend building up the params yourself using `URI.encode_www_form` like so:

    URI.encode_www_form({size: '500x350', scale: 9, markers: ['marker1', 'marker2']})

I think that will probably do what you're describing. The docs definitely could use some work.
