### ISSUE TITLE
How can I pass a username/password down a 302 redirect chain?

### ISSUE THREAD

**Issue by karatedog** [rest-client/rest-client#390]
I have a site, that is available on a www. domain, and its mobile version on the m. domain. Both sites are password protected. A request to the www. site with a mobile User-Agent is redirected to the mobile site.
I have a GET request to the www. domain, with the proper username/password, then I get a redirect, and the mobile site gets a GET without username/password. Both username/passwords are the same, although it might happen elsewhere that these new Locations have different credentials.
I could handle this situation if there was a way to interrupt the redirect process and handle the returned Location?

**Comment by ab** [comment]
The rest-client docs now discuss manually following redirection, which has been improved for rest-client 2.0.

https://github.com/rest-client/rest-client#redirection

If you make a request with `max_redirects: 0` you can manually follow redirection.

```
begin
  RestClient::Request.execute(method: :get, url: 'http://example.com', max_redirects: 0)
rescue RestClient::ExceptionWithResponse => err
  resp = err.response
end
puts "Redirect to: " + resp.headers[:location]
```
