### ISSUE TITLE
RestClient.get should allow for header and params

### ISSUE THREAD

**Issue by MrHubble** [rest-client/rest-client#397]
From the docs we have:

>Request objects know about query parameters and will automatically add them to the URL for GET, HEAD and DELETE requests, escaping the keys and values as needed:
````
RestClient.get 'http://example.com/resource', :params => {:foo => 'bar', :baz => 'qux'}
# will GET http://example.com/resource?foo=bar&baz=qux
````

>Request headers can be set by passing a ruby hash containing keys and values representing header names and values:
````
# GET request with modified headers
RestClient.get 'http://example.com/resource', {:Authorization => 'Bearer cT0febFoD5lxAlNAXHo6g'}
````

Shouldn't we therefore be able to call:

````
RestClient.get 'http://example.com/resource', {:Authorization => 'Bearer cT0febFoD5lxAlNAXHo6g'}, :params => {:foo => 'bar', :baz => 'qux'}
````

When I try this I get `Error: wrong number of arguments (3 for 1..2)`

**Comment by ab** [comment]
Hi there,

You've discovered a really unfortunate part of the RestClient API. I'm planning to rewrite this in a saner way in RestClient 3.0, but that's a long way off.

In the meantime, this should work:

```
RestClient.get 'http://example.com/resource', {:Authorization => 'Bearer cT0febFoD5lxAlNAXHo6g', :params => {:foo => 'bar', :baz => 'qux'}}
```

**Comment by kushbhandari** [comment]
Will below code also work (as per https://github.com/rest-client/rest-client) it looks like:

<pre>
RestClient::Request.execute( { :method => :get, :url => 'http://example.com', :headers => {:params => {:foo => 'bar', :baz => 'qux'}} })
</pre>

Also, how can I see the request URL which was finally executed (with params etc.), I wanted to confirm that request was actually made to `http://example.com?foo=bar&baz=qux` ?

**Comment by ab** [comment]
Yep, that looks right. For testing I usually enable RestClient logging. (e.g. `RestClient.log = 'stderr'`)

**Comment by kushbhandari** [comment]
thanks @ab but is there any way to add parameters if the request URL already has parameters something like:

<pre>
RestClient::Request.execute( { :method => :get, :url => 'http://example.com?param1=value1', :headers => {:params => {:foo => 'bar', :baz => 'qux'}} })
</pre>

The request URL formed from above is `http://example.com?param1=val1?foo=bar&baz=qux` which is incorrect.

**Comment by cben** [comment]
> thanks but is there any way to add parameters if the request URL already has parameters

I'm also interested in that. Tried creating a Resource with a :params "header" instead of having it in the URL, but the headers are `.merge`d together:
https://github.com/rest-client/rest-client/blob/5269c842b/lib/restclient/resource.rb#L50
so the inner :params hash replaces the original params:

```
[4] pry(main)> c = RestClient::Resource.new('httpbin.org/get', headers: {params: {x: 1}})
=> #<RestClient::Resource:0x0055a8eeeb5bf8
 @block=nil,
 @options={:headers=>{:params=>{:x=>1}}},
 @url="httpbin.org/get">

[9] pry(main)>  c.get(params: {y: 2})
RestClient.get "http://httpbin.org/get?y=2", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "User-Agent"=>"rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112"
```
