### ISSUE TITLE
Newbie Doubt

### ISSUE THREAD

**Issue by thebergamo** [rest-client/rest-client#400]
Hi everyone!

I'm a padawan in ruby community, but I need a little help about implementing this module!

On the documentation I see the execute implemented like this: 

```ruby
RestClient::Request.execute(method: :get, url: 'http://example.com/resource',
                            timeout: 10)
```

But, I can pass the parameters like this:

```ruby
RestClient::Request.execute({
          :method => :get,
          :url => :myawesomeurl.com,
          :timeout => 90
        })
```

I can do that?

**Comment by ab** [comment]
I'm not entirely sure what you're asking, but yes, the `foo: bar, baz: 123` syntax is equivalent to `{:foo => bar, :baz => 123}`.

The `:myawesomeurl.com` you have written won't do what you want, though. You should write that as a String `"myawesomeurl.com"` rather than as a Symbol.

**Comment by thebergamo** [comment]
Thanks =D
