### ISSUE TITLE
per request proxy, timeout, hook, etc. configuration

### ISSUE THREAD

**Issue by akostadinov** [rest-client/rest-client#401]
Hello,

currently  proxy and request hooks are configured globally for a ruby process. e.g. `RestClient.proxy="http://myproxy.example.com"` I would like to be able to set these parameters per request.

Update: oops, looking at 2.0.0.rc1 looks like now proxy can be configured per request via the `:proxy` parameter. Did not test but `:before_execution_proc` also seems to be supported. 
**Can be closed.**

**Comment by ab** [comment]
Yeah, the per-request proxy functionality will ship in 2.0.0. We're gradually moving toward a saner interface. :-)
