### ISSUE TITLE
Cookies are lost on follow_redirect

### ISSUE THREAD

**Issue by Jamedjo** [rest-client/rest-client#406]
The fix for #369 breaks cookie persistence as it overwrites all stored cookies with the cookies from the latest request:

    new_args[:headers]['Cookie'] = HTTP::Cookie.cookie_value(cookie_jar.cookies(new_args.fetch(:url)))

Cookies which are happily stored in `new_args[:headers]['Cookie']` on the same domain get dropped when this happens.

Maybe the cookie_jar should include cookies from `request.headers["Cookie"]` with the domain set from `request.url` or maybe Request should also use a cookie_jar.

**Comment by shermanericSF** [comment]
Hey there, any way to up the priority of this ticket or offer a workaround?  I ran into this issue earlier.  Downgrading to 1.7.3 helped, but ideally would like to use the latest version.
Thanks in advance!

**Comment by ab** [comment]
This is fixed by implementing some actual cookie processing in rest-client 2.0.0.
