### ISSUE TITLE
Connection Pooling / Persistent HTTP Conns

### ISSUE THREAD

**Issue by StabbyCutyou** [rest-client/rest-client#407]
Hello, 

I looked through parts of the code and the docs, but couldn't find anything. Does RestClient support either conn pools or otherwise holding a persistent, reusable connection?

It looked to be using raw Net::HTTP, which does not do these things natively (although a community supported persistent variant does exist)

Thanks

**Comment by ab** [comment]
It doesn't currently do these things, though it's possible that it will do so especially for Ruby 2.0, where I think Net::HTTP implements keepalive requests. (Pull requests welcome.)
