### ISSUE TITLE
Empty array is removed from the request

### ISSUE THREAD

**Issue by jwmay2012** [rest-client/rest-client#416]
I'm doing a PATCH request with an object like this:

`{ name: 'asdf', things:[] }`

The recipient of the request sees no 'things' key, just `{ name: 'asdf' }`. Why is the empty array being removed from the request and how can I get RestClient to send it?

**Comment by ab** [comment]
There isn't any true standard for how to handle complex objects like arrays in HTTP params. As a short term workaround, I'd probably recommend just generating the full URI and params yourself if rest-client doesn't implement the desired behavior.

**Comment by ab** [comment]
But more to the point, in payload data, RestClient builds arrays like so:

`{foo: ['a', 'b', 'c']}` yields `foo[]=a&foo[]=b&foo[]=c`

How would you represent an empty list?

PHP's `http_build_query()` method also omits empty lists from the output.

**Comment by ab** [comment]
There's still no way to represent empty containers, but I'm going to try rendering them as null/nil instead. In #437 I'm working on including empty arrays and empty hashes as keys with no value (which is usually interpreted as null/nil). This is rather non-standard, but it seems to work relatively well with the servers I've tested.

So `{foo: 1, bar: [], baz: 3}` yields `foo=1&bar&baz`
