### ISSUE TITLE
put /url, :file => file is altering the file in transit

### ISSUE THREAD

**Issue by crmckenzie** [rest-client/rest-client#420]
I'm uploading zip files to artifactory. I can use curl to put the artifact up and everything is good. If I use rest_client to put the zip files up, it shows up in artifactory, but the zip file is corrupted. Analysis shows that rest_client is sending more bytes than curl--indicating that rest_client is altering the file in transit.

I've attempted to specify headers for Content-Type and whatnot, but rest_client does not appear to be honoring them.

I'm not familiar enough with the deep inner workings of http headers and api calls to understand what's happening.

This is the [api](http://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-DeployArtifact) I'm using

**Comment by ab** [comment]
Can you provide sample code akin to the operation that you're performing?

**Comment by crmckenzie** [comment]
Sure thing.

```ruby
  result = RestClient.put publish_url, :file => File.new(fullpath)
```

**Comment by ab** [comment]
I'm not able to reproduce this. Do you have the actual headers or HTTP form data that rest-client is providing versus curl?

The simplest way to get these would probably be tcpdump / wireshark or by sending the request to a local netcat server to view the raw request data.

Also note that `rest_client` with an underscore `_` is a fork of the main `rest-client`. Not sure if you're using that, but thought it would be good to clarify.

**Comment by ab** [comment]
Feel free to reopen with more information.
