### ISSUE TITLE
Get full url before request

### ISSUE THREAD

**Issue by rusikf** [rest-client/rest-client#423]
Hello ruby hackers !

BEFORE running
```
RestClient.get 'http://google.co.uk', {params: {a:1, b1}}
```
I want to put something like this
```
@user.log "Request to google is #{full_rest_client_url}"
# where full_rest_client_url is http://google.co.uk?a=1&b=1
```
Is it possible ? 
Note: I can set logger like described in README, but it is not what I want.

**Comment by kushbhandari** [comment]
@rusikf this may not be rest-client related question as such, below code might help:

<pre>
url = "http://google.co.uk"
params = {a: 1, b: 1}
url += "?#{params.to_query}"  if(!params.blank?) 
#log("URL => [#{url}]") - prints the URL you are trying to access
RestClient.get url, {params: params}
</pre>

If you URL already contains params, there are other ways to handle that.

**Comment by ab** [comment]
Something like this might be helpful, though the structure of the RestClient code really doesn't make this easy.

    r = RestClient::Request.new(method: :get, url: 'http://google.co.uk', headers: {params: {a:1, b1}})
    log(r.url)

In RestClient 2.0 (not yet released), you'll also be able to use `r.uri` to get the parsed & processed URI object.
