### ISSUE TITLE
Rest-Client is not working with passenger

### ISSUE THREAD

**Issue by fnoelscher** [rest-client/rest-client#426]
When running on rails with the integrated web server (webrick), rest-client works fine.
But with phusion passenger, rest-client will throw errors like 'no method + for nil class'

I'm not the first one to experience this behaviour (see https://groups.google.com/forum/#!topic/phusion-passenger/qB0uUQCBplE)

How can I fix this?

Any help is greatly appreciated.

**Comment by ab** [comment]
This doesn't sound like a bug in rest-client. What's the code you're using for adding the payload?

**Comment by ab** [comment]
Feel free to reopen with more info.
