### ISSUE TITLE
Forced XML response in multipart POST request rather than expected/desired JSON response

### ISSUE THREAD

**Issue by lewaabahmad** [rest-client/rest-client#429]
Hello!

I am trying to make a multipart POST request and in my request I am requesting that the format of my response be JSON. However, the response is XML which does not suit my use case. 

    RestClient.post(POST_URL, {
        :firstname: "Mark",
        :file: File.open("image.jpg"),
        :format => "json",
      }
    )

The response will, however, return to me JSON if I do not try to POST an img file as such: 

    RestClient.post(POST_URL, {
        :firstname: "Mark",
        :format => "json",
      }
    )

**Comment by MOZGIII** [comment]
Try passing `:accept`

**Comment by ab** [comment]
This doesn't really sound like a bug in rest-client. Feel free to reopen if you think it is a rest-client bug. What is the expected way to indicate to this API that you want a JSON response?

You could try adding an `Accept` header like so:

    RestClient.post(POST_URL, {someparam: 'foo'}, {accept: :json})

Or more explicitly:

    RestClient.post(POST_URL, {someparam: 'foo'}, {accept: 'application/json'})
