### ISSUE TITLE
RestClient removes params from headers passed as variable

### ISSUE THREAD

**Issue by brbrr** [rest-client/rest-client#430]
I noticed that `rest-client` deletes `params` key from headers hash. that works fine while you work with raw hash, but if you using variable for headers - that variable would be modified.
how to reproduce:
    
    headers = {
       :connection=>"Keep-Alive",
       :accept_encoding=>"gzip",
       :params=>{:otp=>"66721"}
    }

    RestClient.get("http//example.com", headers) { |resp| resp }
    puts headers

Using headers duplicate (as `.dup`) would easily solve this issue:

    # RestClient::Request#process_url_params:192
    def process_url_params url, headers
        url_params = {}
        headers._dup_.delete_if do |key, value|

**Comment by ab** [comment]
I think this is already fixed on master. Have you tried the pre-release `2.0.0.rc1`?

**Comment by ab** [comment]
Feel free to reopen if this is not the case.
