### ISSUE TITLE
Basic Auth leaves user param in the header

### ISSUE THREAD

**Issue by tomprats** [rest-client/rest-client#438]
I'm using the `RestClient::Request.execute(options)` method with `user` and `password` in my options hash. When it hits my separate Rails API I noticed `"user" => {}` in the params hash. It seemed odd because it's not in the URL, but must be getting passed in through the headers. When querying the API with curl, it didn't show up.

**Comment by ab** [comment]
Can you post more of the code you're using? I'm having a hard time reproducing this.

**Comment by tomprats** [comment]
I actually ended up removing the code, but the pretty vanilla API that I could see the user param from is here: https://github.com/tomprats/personify.  I tried a lot of different config options and still got the param

**Comment by ab** [comment]
Closing, but please don't hesitate to reopen if you'd like to provide code to reproduce.
