### ISSUE TITLE
Closed STDERR

### ISSUE THREAD

**Issue by chengguangnan** [rest-client/rest-client#439]
RestClient closed the STDERR and made the whole Rails app on error. 

What caused this behavior is an RestClient.post to a dead domain, saying http://test_a_b_c_d_e.io.

I don't understand how the code closed STDERR but I think it should be avoided. 

[See how I tracked down to RestClient](http://stackoverflow.com/questions/33459608/how-to-repoen-a-closed-stderr-in-ruby/33488981#33488981)

```
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:211:in
  `ensure in create_file_field'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:211:in
  `create_file_field'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:181:in
  `block in build_stream'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:178:in
  `each'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:178:in
  `each_with_index'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:178:in
  `build_stream'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:53:in
  `initialize'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:14:in
  `new'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb:14:in
  `generate'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:114:in
  `initialize'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in
  `new'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in
  `execute'"
- "/u/apps/MyAppName/shared/bundle/ruby/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:69:in
  `post'"
- "/u/apps/MyAppName/releases/20151111060749/config/initializers/rack_attack.rb:17:in
```

**Comment by ab** [comment]
That backtrace suggests that you are passing `STDERR` somewhere in the payload hash. This tells RestClient that you want to upload STDERR as a file as `multipart/form-data`, so it is dutifully trying to upload the stream and close it.

Is this correct? If so, I don't think that's a bug in RestClient.

**Comment by chengguangnan** [comment]
I was passing a Hash. Here is the code in rack_attack.rb line 17.

      RestClient.post("https://somewhere/", {
        subject: name,
        path: request.path,
        remote_ip: request.ip,
        env: request.env,
        browser: UserAgent.parse(request.user_agent).browser,
        platform: UserAgent.parse(request.user_agent).platform
      })

**Comment by ab** [comment]
What is the `request.env` object? How did you want that serialized as a string?

**Comment by chengguangnan** [comment]
I see. Thanks!
