### ISSUE TITLE
keep-alive connections (feature request?)

### ISSUE THREAD

**Issue by onsails** [rest-client/rest-client#44]
Hello.
I have a problem described here: http://github.com/couchrest/couchrest/issues#issue/43
Couchrest is using rest-client.
It would be great if the library wouldn't create new connection per every request.
So this is possible without using hard socket api. May be it is useful to use Mechanize(without nokogiri) for requests?

**Comment by rosscdh** [comment]
@prettynatty +1 for this did you ever get this implemented?
