### ISSUE TITLE
Posting Multiple Files

### ISSUE THREAD

**Issue by pytong** [rest-client/rest-client#440]
Is it possible to post multiple files without adding extra keys into the file arrays?

This doesn't work
```
    RestClient.post(url,
      {
        :reference_id => "an_id",
        :channel => [
            {
              :audio => File.new("/tmp/1.opus"),
              :video => File.new("/tmp/1.ivf")
            },
            {
              :audio => File.new("/tmp/2.opus"),
              :video => File.new("/tmp/2.ivf")
            }
          ],
        :meta_file => "/tmp/meta.txt"
      })
```
When I checked the request made by the code above, I found this part of the request body missing.
```
      {
        :audio => File.new("/tmp/2.opus"),
        :video => File.new("/tmp/2.ivf")
      }
```

If I post like this, it works. All request content made it to the server. Notice the "0" and "1" in the request body.
```
    RestClient.post(url,
      {
        :reference_id => "an_id",
        :channel => [
            0 => {
              :audio => File.new("/tmp/1.opus"),
              :video => File.new("/tmp/1.ivf")
            },
            1 => {
              :audio => File.new("/tmp/2.opus"),
              :video => File.new("/tmp/2.ivf")
            }
          ],
        :meta_file => "/tmp/meta.txt"
      })
```

**Comment by ab** [comment]
There is no standard that specifies how to handle arrays or deeply nested hashes in multipart/form-data requests, so many web frameworks will handle it in idiosyncratic ways.

rest-client follows the rails / rack convention, which renders `{:array => ["a", "b"]}` as `array[]=a&array[]=b`. It sounds like you may be using a web framework on the server side that doesn't recognize this as valid syntax.
