### ISSUE TITLE
Response fails to properly consolidate multiple headers with the same name

### ISSUE THREAD

**Issue by acaeti** [rest-client/rest-client#447]
I have noticed that when rest-client receives an HTTP response that includes multiple HTTP headers with the same exact name (e.g. two or more "www-authenticate" headers, each with different content), a call to "headers" on the response object will only return the first instance of the header.  I see in the code of abstract_response.rb where you reference http://tools.ietf.org/html/rfc2616#section-4.2 that these values must be able to be concatenated, but I do not see the values from the second header instance.

**Comment by ab** [comment]
What version of rest-client is this? The behavior has changed for the pre-release 2.0.0.rc2 version.

**Comment by acaeti** [comment]
This occurs with 1.8.0.

**Comment by ab** [comment]
In 1.8.0, you should use `resp.raw_headers` if you want to see the array of multiple header values.

**Comment by ab** [comment]
It's only in `2.0.x` that multiple headers with the same name will be concatenated into a single comma-separated value.

**Comment by acaeti** [comment]
good to know.  I guess from reading the abstract_response.rb code in 1.8.0 it sounded like it implemented the RFC and did the concatenation.

Perhaps the code comments and the readme could be altered to make this clear?

**Comment by ab** [comment]
Are you talking about 4b47aad655c9b2dae8d0b3fec3df460c6dfb7eb0? I don't believe those comments are present in the 1.8.x branch.

**Comment by acaeti** [comment]
Just closing the loop, check the comments in 1.8.0 https://github.com/rest-client/rest-client/blob/master/lib/restclient/abstract_response.rb

lines 112-128

quote:

    # Convert headers hash into canonical form.
    #
    # Header names will be converted to lowercase symbols with underscores
    # instead of hyphens.
    #
    # Headers specified multiple times will be joined by comma and space,
    # except for Set-Cookie, which will always be an array.
    #
    # Per RFC 2616, if a server sends multiple headers with the same key, they
    # MUST be able to be joined into a single header by a comma. However,
    # Set-Cookie (RFC 6265) cannot because commas are valid within cookie
    # definitions. The newer RFC 7230 notes (3.2.2) that Set-Cookie should be
    # handled as a special case.
    #
    # http://tools.ietf.org/html/rfc2616#section-4.2
    # http://tools.ietf.org/html/rfc7230#section-3.2.2
    # http://tools.ietf.org/html/rfc6265

**Comment by ab** [comment]
The `master` branch is not `1.8.0`. https://github.com/rest-client/rest-client/blob/master/lib/restclient/version.rb

**Comment by acaeti** [comment]
Please pardon my ignorance!

**Comment by ab** [comment]
No worries! I really wish github made it easier to see what release you're looking at.

On the page for individual commits, they do make it a little easier:

For example, https://github.com/rest-client/rest-client/commit/f27084433937577087cf184e993050d96464f6ef was first released in v1.7.0.rc1 (and the latest pre-release version is v2.0.0.rc2).

![commit](https://cloud.githubusercontent.com/assets/350770/11756971/810d55dc-a012-11e5-9f52-cdf72e48384f.png)
