### ISSUE TITLE
Getting a warning I don't understand

### ISSUE THREAD

**Issue by davidpdrsn** [rest-client/rest-client#454]
After updating my apps dependencies I get this warning when running the tests.

```
[warning] The response contained in an RestClient::Exception is now a RestClient::Response instead of a Net::HTTPResponse, please update your code
```

I'm having trouble finding out which piece of code causes this. Any ideas?

My app is running Rails 4.2.2 and Rest-client 1.8.0.

**Comment by jish** [comment]
I'm having the same issue. It looks like the warning is coming when someone calls a method that is missing from `RestClient::Exception` but **is** present on `Net::HTTPResponse`.

https://github.com/rest-client/rest-client/blob/v1.8.0/lib/restclient/exceptions.rb#L71-L74

```ruby
def method_missing symbol, *args
  if net_http_res.respond_to? symbol
    warn "[warning] The response contained in an RestClient::Exception is now a RestClient::Response instead of a Net::HTTPResponse, please update your code"
    net_http_res.send symbol, *args
```

I overrode `method_missing` on `RestClient::Exception` and it looks like something inside of `RestClient` is calling `to_str` on `RestClient::ServiceUnavailable`

```ruby
class RestClient::Exception
  def method_missing symbol, *args
    stack = caller.join("\n")
    raise "Someone called #{symbol} on #{self.class.name} #{stack}"
```

    Someone called to_str on RestClient::ServiceUnavailable /Users/josh/.gem/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `raise'
    /Users/josh/.gem/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
    /Users/josh/.gem/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
    /Users/josh/.gem/ruby/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'

https://github.com/rest-client/rest-client/blob/v1.8.0/lib/restclient/abstract_response.rb#L74

```ruby
raise Exceptions::EXCEPTIONS_MAP[code].new(self, code)
```

**Comment by ab** [comment]
Eh, what a mess. That's a super legacy part of the codebase.

For what it's worth, the `method_missing` junk is removed in the (currently pre-release) 2.0.0 series. I'm not really sure what to do about it in the meantime; it might be a good idea to remove.

I don't think `to_str` is called by rest-client itself, that seems to simply be a byproduct of raising the exception.

Some tests:

```ruby
class Exc1 < StandardError; end
class Exc2 < StandardError
  def method_missing(symbol, *args)
    warn "method_missing: #{symbol}()"
  end
end
```

```
$ ruby -r ./test.rb -e 'raise Exc1.new'
-e:1:in `<main>': Exc1 (Exc1)

$ ruby -r ./test.rb -e 'raise Exc2.new'
method_missing: to_str()
-e:1:in `<main>': Exc2 (Exc2)

$ ruby -r ./test.rb -e 'begin; raise Exc2.new; rescue Exc2; puts "rescued safely"; end
method_missing: to_str()
rescued safely
```

It should be safe to ignore the warning in any case.

**Comment by floehopper** [comment]
We have a zero tolerance policy towards warnings in our build and so this is causing a problem for us. Since v2.0.0 has not yet been released, is there any other way around this warning?

**Comment by ab** [comment]
Closing, rest-client 2.0.0 was out in July.
