### ISSUE TITLE
Having some problema with nested attributes

### ISSUE THREAD

**Issue by xdougx** [rest-client/rest-client#455]
Hello.
I was reading [this issue](https://github.com/rest-client/rest-client/pull/437), but, i still don't known how to handle with:

```
model[some_nested_attributes][][attr_a]
model[some_nested_attributes][][attr_b]

model[some_nested_attributes][][attr_a]
model[some_nested_attributes][][attr_b]

```

when i send a request, this is what was received:

```
"phones_attributes"=> [
   {"kind"=>"Comercial", "number"=>"11 44225566"}, 
   {"kind"=>"Comercial", "number"=>"11 55554444"}
]
```

when i use rest-client to send to my api:

```
"phones_attributes"=> {"kind"=>"Comercial", "number"=>"11 55554444"}
```

Just one Object, instead an array with two objects, im using a `multipart form` to do this request.

There are any solution to handle with this case?

**Comment by xdougx** [comment]
i dont know if its is useful to help but, i've tried with success this:

```
model[some_nested_attributes][0][attr_a]
model[some_nested_attributes][0][attr_b]

model[some_nested_attributes][1][attr_a]
model[some_nested_attributes][1][attr_b]
```
that was received:

```
 "phones_attributes"=>{
    "0"=> {"kind"=>"comercial", "number"=>"11 44445555"}, 
    "1"=>{"kind"=>"comercial", "number"=>"21 55554444"}
 }
```

thats was sent to api:

```
"phones_attributes"=> {
  "0" => {"kind"=>"comercial", "number"=>"11 44445555"},
  "1"=>{"kind"=>"comercial", "number"=>"21 55554444"}
}
```

**Comment by ab** [comment]
Responding extremely late: have you tried using `RestClient::ParamsArray`, or using a native ruby array? There is no standard that specifies how to handle nested parameters, so different servers will handle it in different ways. Failing all this, you might have to encode the parameters yourself rather than relying on rest-client.

Feel free to reopen with more info.
