### ISSUE TITLE
API vendor, KimonoLabs installed new SSLCert  from RapidSSL and it broke RestClient.get 

### ISSUE THREAD

**Issue by valasensio** [rest-client/rest-client#456]
Vendor KimonoLabs installed a new SSL from RapidSSL and from that moment on my previously working REST code fails with the following on the RestClient.get
----------------------------------------: 
RestClient::SSLCertificateNotVerified in AdminController#load_do_single
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
----------------------------------------
I don't know what to do. It's on the vendor side. Is there a good workaround?

**Comment by valasensio** [comment]
Found possibly related  thread here: https://github.com/rest-client/rest-client/issues/288. If fix is there, I'll mark this closed.

**Comment by ab** [comment]
This doesn't sound like a bug in rest-client. Have you tried using the [SSL Labs test](https://www.ssllabs.com/ssltest/) or `openssl s_client` to troubleshoot? Feel free to reopen with more information if you believe it to be a bug in rest-client.

**Comment by valasensio** [comment]
Hi Andy --

Rest client is fine. I think it's Kimono's new SSL Cert. When that new 
cert was installed it broke my code. No other complaints? I had to 
disable SSL verify in order to make APIs work. That's not a good 
long-term solution, though.

Thanks!
Val

On 1/21/2016 3:06 PM, Andy Brody wrote:
>
> Closed #456 <https://github.com/rest-client/rest-client/issues/456>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rest-client/rest-client/issues/456#event-522195740>.
>


-- 
With Kind Regards,
Valerie Asensio
*Founder & Developer, Wishalizer.org*
Wish list aggregating app for animal shelters and rescue organizations

**Comment by etalley** [comment]
I just ran across this with a new cert (1/28/2016). My theory is that while browsers certs are updated regularly ruby (2.2.3) is currently out of date. I just reproduced the issue on Ubuntu and CentOS. still deciding whether to disable or try to load the pem.

**Comment by ab** [comment]
@etalley By default, rest-client will use your system CA certificates, so on a first pass that doesn't seem likely. I believe if you're using rvm, though, it ships with its own certificates. What
