### ISSUE TITLE
Configuring gem in Rails?

### ISSUE THREAD

**Issue by edelgado** [rest-client/rest-client#457]
Typically, if you want to set a framework-wide configuration flag to a gem in Rails, an initializer file is created with something like:

```ruby
MyGem.configure do |config|
  config.option_one = :foo
  config.option_two = :bar
end
```

There doesn't be such a thing for `RestClient`. Any ideas as to how to achieve this?

**Comment by ab** [comment]
What sort of configuration did you have in mind? I'd say most people will write a thin wrapper method to apply any desired defaults.

For example:

```
def my_get(url)
  RestClient::Request.execute(method: :get, url: url, timeout: 30)
end
```

**Comment by edelgado** [comment]
Hmm, seems like it would be cleaner if we could set any configuration framework-wide without having to create some sort of module to place the thin wrapper in.
