### ISSUE TITLE
:ssl_version => 'TLSv1'  not mentioned?

### ISSUE THREAD

**Issue by bjm88** [rest-client/rest-client#458]
Why is setting ssl_version not mentioned in the read.me doc?  Is SSLv3 still the default? on v1.8.0 that is?

**Comment by bjm88** [comment]
If I put this in a rails initializer would RestClient lib respect it / use it?

OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version] = 'TLSv1_2'

**Comment by ab** [comment]
The default (as of rest-client 1.7.0) is to use Ruby's default SSL version, which is any available version (starting with the highest). There isn't any reason to override this unless you specifically want to disallow lower versions like TLSv1.

You can set this on a per request basis with something like this:

```
RestClient::Request.execute(method: :get, url: 'https://example.com', ssl_version: 'TLSv1_2')
```

**Comment by ab** [comment]
Oh, and to actually answer your question: your approach should indeed work.
