### ISSUE TITLE
2.0.0.rc2 does not redirect automatically

### ISSUE THREAD

**Issue by akostadinov** [rest-client/rest-client#461]
I just observe that I'm getting 302 redirect with 
```
 :headers=>
  {"location"=>
    ["https://xyz:8443/console/"],
   "date"=>["Mon, 01 Feb 2016 17:21:21 GMT"],
   "content-length"=>["86"],
   "content-type"=>["text/html; charset=utf-8"]}
```

`max_redirects` are at 10. Any idea why is this? Would 2.0.0 GA be released anytime soon?

**Comment by akostadinov** [comment]
I found the issue. In `AbstractResponse#return!` method, there is a check for request method. Issue is that it only checks for `[:get, :head]` while if one specifies `GET` or `HEAD` that doesn't catch it.

**Comment by ab** [comment]
Thanks for raising this! I ended up fixing this in a way that addresses more of the underlying issues as well. The old code had no good reason to be passing request args separately from the request when the request makes its args hash accessible.
