### ISSUE TITLE
Support mime-types 3.0

### ISSUE THREAD

**Issue by ioquatix** [rest-client/rest-client#464]
This is holding me back on all apps that depend on coveralls:

```
    coveralls was resolved to 0.8.10, which depends on
      rest-client (< 2, >= 1.6.8) was resolved to 1.8.0, which depends on
        mime-types (< 3.0, >= 1.16)
```

Thanks so much.

**Comment by nickhammond** [comment]
mime-types 3.0 only supports Ruby 2.0+ while rest-client still supports MRI 1.9.3 so this would be a major version change. Also, all of the deprecated methods in mime-types 2.X have been removed. Until rest-client drops support for 1.9.3 this upgrade won't be possible.

https://github.com/mime-types/ruby-mime-types/blob/master/History.rdoc

**Comment by ioquatix** [comment]
fair enough.

But this is a problem. Is 1.9.x still relevant? People can still use existing releases.

**Comment by nickhammond** [comment]
Looks like there's a RC for 2.0.0 which drops support for 1.9.2 but still planning on supporting 1.9.3. Maybe 2.0.0.rc2 can drop 1.9 support altogether, 1.9 users could still use legacy versions. Looks like most of the changes in 2.0 so far are improvements and some internal refactoring. 1.9.3 EOL was actually last February too - https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by ioquatix** [comment]
I think that's a good plan. Looking forward to the 2.0 release

**Comment by ioquatix** [comment]
Hello, just wondering when the 2.0 release will be out, it looks like you've made some good progress in this direction.
