### ISSUE TITLE
Building pre-compiled gem

### ISSUE THREAD

**Issue by SvenPetroll** [rest-client/rest-client#473]
Hi,

I'm trying to include rest-client in an extension for Sketchup. Since they're using their own interpreter, native libraries *usually* can't be used, since they don't include dev-tools. Other libraries sometimes are offering pre-compiled gems that can be used in this situation.

I tried using gem-compile, but according to them, `There are no extensions to build on this gem file.`.. Any idea?

**Comment by ab** [comment]
I'm not familiar with gem-compile, but rest-client does not itself include any C extensions or native libraries.

Maybe you're looking to compile the C extensions of the dependencies? There is a dependency `unf_ext` that has C extensions.

Relevant dependency tree showing versions as of today:

```
rest-client (1.8.0)
  http-cookie (1.0.2)
    domain_name (0.5.20160310)
      unf (0.1.4)
        unf_ext (0.0.7.2)
```
