### ISSUE TITLE
URL with square brackets: URI::InvalidURIError

### ISSUE THREAD

**Issue by lucaspiller** [rest-client/rest-client#476]
When making a request to a URL with square brackets, an exception is raised:

```ruby
> RestClient.get 'http://example.com/resource[1].doc'
URI::InvalidURIError: bad URI(is not URI?): http://example.com/resource[1].doc
```

The same happens even if the URL is escaped first:

```ruby
> RestClient.get URI.escape('http://example.com/resource[1].doc')
URI::InvalidURIError: bad URI(is not URI?): http://example.com/resource[1].doc
```

I've tested rest-client 1.8.0 and 2.0.0.rc2 under Ruby 2.1.5 and 2.3.0, and it happens in all cases.

**Comment by jrafanie** [comment]
@lucaspiller I believe those are invalid URLs as per: http://tools.ietf.org/html/rfc3986#appendix-D.1

Unfortunately, it looks like URI only encodes invalid characters, not ones like [], which are valid only for the host component (for IPv6 addresses).  Note, addressable, an alternative to URI, seems to do what you want.

```ruby
irb(main):001:0> require 'uri'
=> true
irb(main):003:0> URI.encode('http://example.com/resource[1].doc')
=> "http://example.com/resource[1].doc"
irb(main):004:0> require 'addressable'
=> true
irb(main):005:0> Addressable::URI.encode('http://example.com/resource[1].doc')
=> "http://example.com/resource%5B1%5D.doc"
```

You have to encode the components yourself if you're using URI:
```ruby
irb(main):013:0> URI("http://example.com") + URI.encode_www_form_component('resource[1].doc')
=> #<URI::HTTP http://example.com/resource%5B1%5D.doc>
irb(main):014:0>
```

See also: https://bugs.ruby-lang.org/issues/11819

**Comment by lucaspiller** [comment]
Thanks! I've raised a Ruby bug: https://bugs.ruby-lang.org/issues/12235

**Comment by jrafanie** [comment]
:+1: Good luck @lucaspiller.
