### ISSUE TITLE
Backport add before_execution_proc support to Requests

### ISSUE THREAD

**Issue by justinleveck** [rest-client/rest-client#477]
Would you consider backporting this feature written by @ab as the Stripe gem cannot use version 2x of RestClient? It would really help us out with making OAuth requests.

https://github.com/rest-client/rest-client/commit/58c61be229d77744d2d3199620da1974e244292d

**Comment by justinleveck** [comment]
Opened a PR https://github.com/rest-client/rest-client/pull/478

**Comment by ab** [comment]
Belatedly, thanks, but the stripe gem no longer uses rest-client, and I'm not inclined to backport features to old rest-client releases.
