### ISSUE TITLE
response.to_i does weird stuff

### ISSUE THREAD

**Issue by nekogami** [rest-client/rest-client#480]
Here is a sample

```
  response = RestClient.post(request_url, params, content_type: :json)
  #the remove server response is 42
  response.to_s        #=> "42"
  response.to_str      #=> "42"
  response.to_i        #=> 200 wat ?

  response.body        #=> "42"
  response.body.to_i   #=> 200 uh ?

  String.new(response).to_i = 42
```
While I agree that I should get a full-fledge valid json, to_i has a really weird behavior right ?

**Comment by ab** [comment]
Yep, it's really weird. This is already changed on master and will be more sane in 2.0.0.

**Comment by ajahongir** [comment]
Having same issue.

**Comment by nekogami** [comment]
For now i think your only solution aside from using the master branch in your gemfile or waiting for 2.0 is to do as I did
String.new(response).to_i
