### ISSUE TITLE
undefined method '+' down in net/http.rb when using Request.execute

### ISSUE THREAD

**Issue by p7r** [rest-client/rest-client#485]
I've got a problem I've tried to diagnose, but I'm drawing a blank, and thinking somebody here might be able to help. I'm trying to make a REST call to an API that requires SSL and a few custom headers. This was working fine until this morning and now for whatever reason refuses to work and I'm not sure what has changed.

When my code tries to do this:

`RestClient::Request.execute(method: :get, url: "#{@url}/#{remote_method}?username=#{@login}&#{params}", headers: {:password => @password, :id => @id}, verify_ssl: false)`

If it matters, `@url` is set to a string that is `"https://server.i.need.to.keep.private.com:443/rest/v1"` and can confirm the other variables in that string are all non-nil.

I get this stack trace:

```
error: undefined method `+' for nil:NilClass
/home/p7r/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1561:in `addr_port': undefined method `+' for nil:NilClass (NoMethodError)
        from /home/p7r/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1494:in `begin_transport'
        from /home/p7r/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1433:in `transport_request'
        from /home/p7r/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
        from /home/p7r/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:270:in `net_http_do_request'
        from /home/p7r/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:418:in `block in transmit'
        from /home/p7r/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
        from /home/p7r/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
        from /home/p7r/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
        from /home/p7r/.rvm/gems/ruby-2.3.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        [... snip ... ]
```

My Gemfile.lock shows rest-client as follows:

```
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
```

What really confuses me is that this was working just fine until this morning and then stopped working. I've tried different versions of Ruby, but no dice.

**Comment by p7r** [comment]
Is there any more detail I can provide to help debug this?

**Comment by ab** [comment]
Based on that backtrace it sounds like you are somehow passing an empty hostname in the URL. It's a bit hard to debug if you need to keep that secret, but I'd look into what the rendered URL actually is after the string interpolation.

**Comment by ab** [comment]
Closing, but feel free to reopen with more info.
