### ISSUE TITLE
Question - Any status updates on the official release of 2.0.0?

### ISSUE THREAD

**Issue by trabulmonkee** [rest-client/rest-client#493]
Ruby gems shows 1.8.0 as still the main release.  I see there have been 2 release candidates for 2.0.0.
Any status updates on the official release of 2.0.0, instead of just a release candidate?

**Comment by ioquatix** [comment]
This is blocking the migration to mime-types 3.0 for us which is a pain.

**Comment by ab** [comment]
I just cut a new release candidate, version 2.0.0.rc3. It contains a very large number of exciting/scary changes that you normally wouldn't want to add in between release candidates. So please give it a whirl!

https://github.com/rest-client/rest-client/compare/v2.0.0.rc2...v2.0.0.rc3

https://rubygems.org/gems/rest-client/versions/2.0.0.rc3

I'm not currently tracking any other changes for 2.0.0, so let me know if all looks well in testing. I'll send out a RC3 note to the email list soon.

https://github.com/rest-client/rest-client/milestones/2.0.0

**Comment by ioquatix** [comment]
The only thing I'd suggest is whether you'd like to merge in https://github.com/rest-client/rest-client/issues/488 as this would be a pretty cool feature and lots of people would be interested in it, but we could aim for 2.1 for that. I'd be happy to submit a PR.

**Comment by ioquatix** [comment]
I'll test this, this week, and let you know.

**Comment by ab** [comment]
https://rubygems.org/gems/rest-client/versions/2.0.0
