### ISSUE TITLE
Only log request information

### ISSUE THREAD

**Issue by Katee** [rest-client/rest-client#496]
I use rest-client when communicating with various services, some of these services return binary data instead of text. I have logging enabled (because knowing the URL, parameters and time is super useful) but for these binary responses having the body logged isn't very helpful at all. Is it possible to set the logging level so that it logs the request but not the response body?

**Comment by hanumakanthvvn** [comment]
Any update on this? can i have a chance to work on this?

**Comment by hanumakanthvvn** [comment]
@ab Sorry, I took chance without your permission to this enhancement PR. Please review/change code accordingly if necessary.

**Comment by ab** [comment]
I'm a little confused by the issue here. rest-client never logs the response body, does it? I thought it only logs the response code, content-type header, and size of the body.

**Comment by ab** [comment]
Closing this due to age, but feel free to reopen.
