### ISSUE TITLE
user credentials overwritten in request

### ISSUE THREAD

**Issue by mkamensky** [rest-client/rest-client#500]
The lines

    @user = args[:user]
    @password = args[:password]

in Request.initalize override the values previously obtained from `parse_url_with_auth!`, even if the arguments don't exist. Perhaps they should be replaced with

    @user = args[:user] if args.has_key?(:user)
    @password = args[:password] if args.has_key?(:password)

**Comment by ab** [comment]
Dang, good catch. Looks like the relevant tests break abstraction barriers in a way that caused them to miss this.
