### ISSUE TITLE
is it semantically versioned?

### ISSUE THREAD

**Issue by matkoniecz** [rest-client/rest-client#503]
During building my gem I encountered

```
WARNING:  pessimistic dependency on rest-client (~> 1.8.0) may be overly strict
  if rest-client is semantically versioned, use:
    add_runtime_dependency 'rest-client', '~> 1.8', '>= 1.8.0'
```

In readme and in repository search I failed to find answer for this question.

**Comment by ab** [comment]
Yes, it's semantically versioned. I'd suggest using `~> 1.8` as the dependency.
