### ISSUE TITLE
Release version 2.0.0 at rubygems.org

### ISSUE THREAD

**Issue by DanielVartanov** [rest-client/rest-client#507]
Currently rubygems.org doesn't know about rest-client 2.0.0, which brings problems because gem maintainers usually don't want to change .gemspec file in a way when it references Github repo instead of version number.

Please release it to rubygems.org
Thanks.

**Comment by DanielVartanov** [comment]
@ab, do you control rubygems.org account of rest-client? Can you release the gem please?

**Comment by ab** [comment]
@DanielVartanov and others, have you tested 2.0.0.rc4? `gem install --pre rest-client`

If there are no showstopper bugs, it sounds like we're ready for the final release this week.

**Comment by domcleal** [comment]
I've updated the apipie-bindings gem to support 2.0.0 and rc4's been working fine in my testing.

**Comment by ab** [comment]
https://rubygems.org/gems/rest-client/versions/2.0.0
