### ISSUE TITLE
Timeout not working 

### ISSUE THREAD

**Issue by kaluznyo** [rest-client/rest-client#509]
I try to increase timeout time. I set open_timeout and timeout to 30, or to nil. But I get RestClient::Exceptions::OpenTimeout: Timed out connecting to server after less than 10 secondes. Is it normal ?

Using rest-client 2.0

**Comment by ab** [comment]
Can you paste an example code snippet that shows the issue?

**Comment by ab** [comment]
Closing, but feel free to reopen with more info.

**Comment by andricicezar** [comment]
```

**Comment by andricicezar** [comment]
Interesting fact, if the service is on and I set the timeout to 0, it kills instantly the request.
