### ISSUE TITLE
Sign oAuth requests

### ISSUE THREAD

**Issue by goocastro** [rest-client/rest-client#512]
I am trying to sign oAuth requests following the example. All `rest-client` requests signed with oAuth gem are always `401 Unauthorized`. But requests sent directly with `access_token` object passes. I checked the headers, they seem to be consistent, I'm stuck trying to debug It. Any ideas?

``` ruby
require 'oauth'
require 'rest-client'

cons = OAuth::Consumer.new(
  "consumer",
  "consumer-secret",
  {
    scheme: :header,
    site: 'https://api.twitter.com'
  })

access_token = OAuth::AccessToken.from_hash(cons,
                                            {oauth_token: "token", 
                                             oauth_token_secret: "token-secret"}
                                           )
# THIS WORKS
p access_token.request(:post, "https://api.twitter.com/1.1/statuses/update.json", {status: 'request from oauth'})

# THIS DOESN'T
RestClient.add_before_execution_proc do |req, params|
  access_token.sign!(req)
end
p RestClient.post('https://api.twitter.com/1.1/statuses/update.json', {status: 'rest-client/oauth'})


```

**Comment by ab** [comment]
Doesn't really seem like this is a rest-client bug. The only difference between the two that stands out to me is that one has `oauth_body_hash` in the `Authorization` header and the other doesn't. But I'm really not very knowledgeable about oauth.

Does this work with the rest-client 1.x series?

**Comment by ab** [comment]
Feel free to reopen with more info.
