### ISSUE TITLE
interactive mode not working

### ISSUE THREAD

**Issue by brandondrew** [rest-client/rest-client#513]
According to the README,

> ## Shell

> The restclient shell command gives an IRB session with RestClient already loaded:

> ```ruby
$ restclient
>> RestClient.get 'http://example.com'
```

but in reality, this doesn't work:

```
$ restclient
Thoom::RestClient v0.14.2
@author Z.d. Peacock <zdp@thoomtech.com>
@link http://github.com/thoom/restclient

Missing required options. Use "--help" OR "--help details" for more information
```

**Comment by ab** [comment]
You appear to have installed `restclient` rather than this gem, `rest-client`.

https://github.com/thoom/restclient
https://rubygems.org/gems/restclient
https://rubygems.org/gems/rest-client
