### ISSUE TITLE
Support for multiple loggers/logger per-resource?

### ISSUE THREAD

**Issue by rgalanakis** [rest-client/rest-client#517]
We use RestClient to wrap a number of third-party APIs, and currently with a global logger, we cannot configure things like the log level of API wrappers separately. We can of course configure the logging for the wrappers, but not the RestClient calls they make (and if we set debug level logging to debug one service, we get debug level logging for _all_ restclient calls.

So, two questions:
1. Is per-Resource logging something this project would be interested in if it could be done in a backwards-compatible way? I don't see other requests for it, but I feel like this is a super useful feature.
2. If yes, I was thinking an implementation approach could be to create a new `Resource` with a logger, then the Resource could pass the logger into `Request.execute` which would use it for logging. The `Request` could also pass it through to `Response.create`. If that doesn't sound like a good plan, can you suggest another approach?

If this is something the project is interested in, I'd love to put up a PR.

**Comment by ab** [comment]
Ugh, yes, over time I've been slowly trying to get rid of RestClient's global configuration in favor of per-request configuration. PRs welcome.
