### ISSUE TITLE
How to post with compress and data-binary

### ISSUE THREAD

**Issue by ziweizhou** [rest-client/rest-client#518]
Hello Restclient team

is it possible to do a POST using rest-client which will simulate the behavior of 

`curl --compressd --data-binary '{"name":"Jack", "address": "123 Whatever Road"}'` ? 

Thanks 
Ziwei

**Comment by ab** [comment]
I don't think rest-client has any helpers for this, but you can certainly gzip compress the request payload yourself and add the `Content-Encoding: gzip` yourself.

    RestClient.post(url, gzipped_data, {content_encoding: 'gzip'})

**Comment by lookas1** [comment]
@ab is it still not possible? I can't find it in any documentation for rest-client.
