### ISSUE TITLE
Quotes added to cookies values that contain spaces

### ISSUE THREAD

**Issue by dominic-oconnor** [rest-client/rest-client#521]
After upgrading from 1.8 to 2.0, for any cookies that have a space in the value, the cookie value is wrapped in quotes. The quotes are added before the request occurs and each request causes additional quotes to be added. I added logging in request.rb to trace the source of the issue:
````
    def make_cookie_header
      return nil if cookie_jar.nil?

      arr = cookie_jar.cookies(url)

      return nil if arr.empty?

      puts "********COOKIEJAR: #{cookie_jar.cookies(url)}"
      cookie_header= HTTP::Cookie.cookie_value(arr)
      puts "********COOKIE_HEADER: #{cookie_header.inspect}"      
      return cookie_header
    end
````
produces this output
````
********COOKIEJAR: [#<HTTP::Cookie:name="FULLNAME", value="Trogdor Burninator", domain="example.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2016-08-12 13:25:11 -0400, accessed_at=2016-08-12 13:01:13 -0400 origin=nil>]
********COOKIE_HEADER: "FULLNAME=\"Trogdor Burninator\"
````
and sending another request yields this:
````
********COOKIEJAR: [#<HTTP::Cookie:name="FULLNAME", value="\"Trogdor Burninator\"", domain="example.com", for_domain=true, path="/", secure=true, httponly=true, expires=nil, max_age=nil, created_at=2016-08-12 13:25:12 -0400, accessed_at=2016-08-12 13:01:13 -0400 origin=nil>]
********COOKIE_HEADER: "FULLNAME=\"\\\"Trogdor Burninator\\\"\"
````

**Comment by ab** [comment]
Hmmm, spaces are a tricky area with Cookies, because they're handled inconsistently by different clients and servers. Per RFC6265, cookie values are not supposed to contain spaces. But they may optionally be quoted by server or client.

Here's how Chrome transmits a cookie value with a space vs without:
```
GET / HTTP/1.1
Host: example.com
Connection: keep-alive
...
Cookie: withspace="with space"; nospace=nospace
```

And here's how rest-client handles it:
```
GET / HTTP/1.1
Accept: */*
User-Agent: rest-client/2.0.0 (darwin15.4.0 x86_64) ruby/2.2.5p319
Cookie: nospace=nospace; withspace="with space"
Host: example.com
```

Are you sure your server is parsing this cookie header correctly? It seems like this bug is on the server side.

See also a test with httpbin.org, which rest-client round trips without issue:

```ruby
>> r = RestClient.get('https://httpbin.org/cookies/set?withspace=with%20space&nospace=nospace'); puts r.body
{
  "cookies": {
    "nospace": "nospace", 
    "withspace": "with space"
  }
}
```

**Comment by ab** [comment]
P.S. RFC 6265 recommends base64 encoding cookie values that may contain arbitrary text to avoid issues like these with clients handling the data differently.

**Comment by ab** [comment]
Closing, but feel free to reopen with evidence that rest-client is doing something that browsers do not.
