### ISSUE TITLE
Integer in payload is changed to String.

### ISSUE THREAD

**Issue by bibobibo** [rest-client/rest-client#522]
When I call RestClient::Request.execute and put an object into payload, there is Interger type value in request object, but server get String type. How to resolve it?

**Comment by bibobibo** [comment]
It works when I call RestClient.put directly

**Comment by ab** [comment]
Can you post the code that you're using in each of these cases? All HTTP request data is natively strings.

**Comment by jeffmess** [comment]
@bibobibo You need to convert your POST params to json.

`RestClient.post url, params.to_json, headers`
