### ISSUE TITLE
Should rest-client support skip appending square bracket for array params?

### ISSUE THREAD

**Issue by Martin288** [rest-client/rest-client#526]
Most cases, services are conformed to the same convention that appending square bracket for array params, such as, `q[]=key1&q[]=key2&q[]=key3`, which is more semantic. But unfortunately, some services, not always accept such kind of params.

One of my service provider requires that params like `q=key1&q=key2&q=key3`.

I can not find any option to disable default behaviour to not to append brackets in this gem. I wonder if anyone else has meet the same problem?

**Comment by ab** [comment]
I'd recommend just not using the rest-client params functionality and just constructing the full URL yourself in this case.

For example:
```ruby
params = URI.encode_www_form([['q', 'key1'], ['q', 'key2'], ['q', 'key3']])
RestClient.get("http://example.com/foo?#{params}"
```
