### ISSUE TITLE
Nested array of hash not working

### ISSUE THREAD

**Issue by ankitrg** [rest-client/rest-client#530]
I am using facebook api to get some data. I am using the `filtering` params for insights. My params hash looks like this:
```
p = {:level=>"campaign", :filtering=>[{:field=>"campaign.effective_status", :operator=>"IN", :value=>["ACTIVE"]}]}
```

The similar params are working for me on the graph api like so:
```
act_74334623125/insights?level=campaign&filtering=[{'field':'campaign.effective_status', 'operator':'IN', 'value':['PAUSED']}]
```

The request in the search bar looks something like this:
```
method=GET&path=act_7493442565%2Finsights%3Flevel%3Dcampaign%26filtering%3D[%7B%27field%27%3A%27campaign.effective_status%27%2C%20%27operator%27%3A%27IN%27%2C%20%27value%27%3A[%27PAUSED%27]%7D]&version=v2.7
```

where as the one generated by me via rest-client throws BAD Reqest and looks like so:
```
RestClient.get "https://graph.facebook.com/v2.7/act_752526262685/insights?level=campaign&time_range[since]=2016-09-06&time_range[until]=2016-10-05&filtering[][field]=campaign.effective_status&filtering[][operator]=IN&filtering[][value][]=ACTIVE&access_token=EAAQIOO3uyD&format=json", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "User-Agent"=>"rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112"
# => 400 BadRequest | application/json 141 bytes
```

Has anyone seen similar issues happen? Need help!

**Comment by ab** [comment]
I'm not familiar with the FB graph API, but it looks like those parameters are intended to be JSON?

There's no universal standard for nested hashes, so different APIs and servers will handle it very differently. RestClient natively takes an approach that works well with rails and PHP servers with x-www-form-urlencoded form data.

You might try doing something more like this, which turns the `:filtering` array into a JSON string:

    require 'json'
    p = {:level=>"campaign", :filtering=>[{:field=>"campaign.effective_status", :operator=>"IN", :value=>["ACTIVE"]}].to_json}

**Comment by ankitrg** [comment]
I could not get that to work, but I reached to something that works:

```ruby
hash = "{'field': 'campaign.effective_status', 'operator': 'IN', 'value': ['#{FbAds::Campaign::Status::Active}']}"
```

Thanks for the help.
