### ISSUE TITLE
Block cause inconvenience for response

### ISSUE THREAD

**Issue by mikedeng** [rest-client/rest-client#532]
Here is  my raw code, and the response shall get nil if the inner response access directly .

```ruby
response = RestClient.post(url, params, opts) do |r|
    [301, 302, 307].include?(r.code) if r.follow_redirection
end
```

It cost me a couple of hours to check if there it access directly or not, and I finally got it,it's about the **if**, I should always had return from the block.

```ruby
response = RestClient.post(url, params, opts) do |r|
       [301, 302, 307].include?(r.code) ? r.follow_redirection : r
end
```
       
the network is tricky, and I always wanna get my response whether the block returns or not, hope you guys' consideration.

**Comment by ab** [comment]
I'm not sure I fully understand what the objective is here.

`follow_redirection` is a method that has side effects, and will fire off a new request.

Did you mean to write something more like this?

```
r = RestClient.post(url, params, opts)
if [301, 302, 307].include?(r.code)
  r.follow_redirection
end
```

**Comment by mikedeng** [comment]
Thanks @ab 
All I want is what you suggested, but it should add the exception-handling code with yours. I now know that `the block` shall inevitably cause side effect of the response. Just close this issue. Thank again.

**Comment by ab** [comment]
Glad it's working!
