### ISSUE TITLE
Rest client is crashin when send por with json with more than one argument

### ISSUE THREAD

**Issue by juhlila** [rest-client/rest-client#536]
```
params= { test: 'oi',
number: 2
}  

url = TESTING_HTTP_SERVER_URL + endpoint
  RestClient.post url, params
```

It crashes, same happened when I used net/http. If theres only one key, it passes, if i type:
`RestClient.post url, { test: 'oi', number: 2}` 
it passes, but if i send my params to a variable, it crashes everytime, maybe its because ruby changes the hash output? for example, when I attribute a value to params, written exactly like it is above, i see on terminal the output `=> {:test=>"oi", :number=>2}`, which makes it crash, although it makes no sense

The error is 
`RestClient::ServerBrokeConnection: Server broke connection
from /Users/julia/.rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:780:in `rescue in transmit'`

**Comment by ab** [comment]
RestClient isn't crashing here. It's throwing an exception when the server rudely closes the connection without sending a response. Have you looked at the server logs for an error?

Note that RestClient doesn't do anything with JSON. So if you want your params to be encoded as json you should `require 'json'` and use something like `params.to_json` instead.

**Comment by ab** [comment]
Closing for now, but feel free to reopen with more info.
