### ISSUE TITLE
Authorization headers cached

### ISSUE THREAD

**Issue by cmeerbeek** [rest-client/rest-client#541]
I am using FluentD to get data from an API using an input plugin and sent data to another API using an output plugin.

The input plugin uses oauth to authenticate and this works flawless. The output plugin uses an basic Authorization header with a simple token. 

The logging says: RestClient.post "http://<url>:<port>/services/collector/event", 7571 byte(s) length, "Accept"=>"_/_", "Accept-Encoding"=>"gzip, deflate", "Authorization"=>"Splunk <token>", "Content-Length"=>"7571", "User-Agent"=>"rest-client/2.0.0 (linux-gnu x86_64) ruby/2.1.10p492" which should work fine. 
The result is a 401 Unauthorized nonetheless. I was getting insane.

I created pcap file to debug this and in the pcap it turned out that RestClient was reusing the oauth headers from the input plugin in the output plugin as well.

How is this possible? Is there a way to fix this, like force-clear headers?

**Comment by ab** [comment]
Can you provide more information about these plugins? I don't know what those libraries are doing.

**Comment by cmeerbeek** [comment]
Output plugin: https://gist.github.com/cmeerbeek/08633a63ba2e7bfad035359809e26538
Input plugin: https://gist.github.com/cmeerbeek/1a3623811ff08f9ce1d94994e26cfe5d

Unfortunately I cannot post the code of FluentD ;-)

So the output plugin I confituren to use a simple Authorization header with a token. Instead looking at the pcap on the destination I see the oauth headers from the input plugin.

I have the pcap but I rather sent it to you directly and not on GitHub.

**Comment by ab** [comment]
Sorry, I'm really not familiar with these libraries. If there's evidence of a bug in rest-client itself, please feel free to reopen.
