### ISSUE TITLE
netrc settings overwrite Authorization headers

### ISSUE THREAD

**Issue by robotex82** [rest-client/rest-client#550]
Assume you have an netrc entry for a given host and you make a request to that host passing Authorization headers like this:

    RestClient.post api_endpoint, request_params, { :Authorization => build_api_key_authorization_header }

the created request does not include the Authorization Header passed to the method. Instead the credentials stored in netrc are used.

I'm using ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux] with the most recent master from github after having tried the latest gem.

Is there any way to override this or can you point me in a direction where to look in the code, so i can patch it?

Thanks in advance!

Best regards
Roberto

**Comment by ab** [comment]
See also #524

**Comment by ab** [comment]
A partial fix for this was attempted in #374 but was case-sensitive and only worked for `"Authorization"`.

In trying to fix this I ran into an unexpected wrinkle: `stringify_headers` only normalizes the capitalization for Symbol keys, not Strings. Leaving this as is for compatibility for now. https://github.com/rest-client/rest-client/issues/599

The auth code in general could use a big refactor to be more modular.

Fix for this will be released in 2.1.0.
