### ISSUE TITLE
Performing a LINK request

### ISSUE THREAD

**Issue by nielsbuus** [rest-client/rest-client#564]
I'm working an API client for some (needlessly) experimental API.

I need to do an HTTP LINK request.

See: https://tools.ietf.org/id/draft-snell-link-method-01.html#rfc.section.2

Seeing as it's not defined on the module, I tried this (inspired by rest-client's own implementation of the get, post, head, etc...):

    RestClient::Request.execute(
          method: :link,
          url: "https://target.dev/api/link/123/with/456",
          headers: generate_headers
        )

This sadly triggers a

    NameError: uninitialized constant Net::HTTP::Link

It seems that rest-client is fundamentally incapable of supporting LINK requests, since it constantizes the HTTP verb on https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb#L510 and Net::HTTP does not include any implementation for LINK requests.

Can anyone confirm my conclusion or am I missing something?

**Comment by ab** [comment]
Yeah, I'd be surprised if there's any way to do this with rest-client. Do you know if Net::HTTP has any support for specifying custom HTTP verbs?

**Comment by nielsbuus** [comment]
I have dug into it and found that `Net::HTTP` doesn't have any programmatic API or DSL for doing it, but the way each verb is implemented makes it trivial to add more verbs.

To support the link action, one has to define the following class:

    class Net::HTTP::Link < Net::HTTPRequest
      METHOD = "LINK"
      REQUEST_HAS_BODY = false
      RESPONSE_HAS_BODY = false
    end

With this defined, rest-client will support `link`.

It works, it's simple. I doubt it's officially endorsed though, so it's hard to know if time will be lenient against this expansion of the standard library in Ruby.

**Comment by ab** [comment]
Neat!
