### ISSUE TITLE
How to correctly structure a complicated post request?

### ISSUE THREAD

**Issue by PAMulligan** [rest-client/rest-client#574]
I'm currently trying to post to a small internal api that we've built, that's supposed to convert a file to pdf. I have no problem posting to it with a very small file, but I'm running into timeout issues. My current call looks like this:
    
    response = RestClient.post(uri.join,
    {
        :file => File.new(file_path, 'rb')
    })

It is my understanding that to set the timeout, I need to use RestClient.execute instead of .post, so I refactored the request to look like this:

    response = RestClient.execute(method: :post,
                                                     timeout: nil,
                                                     url :uri.join,
                                                     payload: { file: File.new(file_path, 'rb') })

However, this just stalls, without an error code for 10 minutes. Any idea how I'm structuring the request incorrectly?

**Comment by balogic** [comment]
It is correct and I also use the same format for an app but the only thing is that you need to set timeout as `timeout: 10` so that it requests withing a specific time limit

**Comment by PAMulligan** [comment]
Thank you, is there a way to disable the timeout at all, or do I just need to set it really high?

**Comment by balogic** [comment]
Setting `timeout: -1` will do but it is good to use a constant if you want it to be high

**Comment by ab** [comment]
Note that using `-1` is deprecated. The current usage is `timeout: nil`.
