### ISSUE TITLE
RestClient::SSLCertificateNotVerified: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by zhanjianmin** [rest-client/rest-client#575]
from /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:809:in `rescue in transmit'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:698:in `transmit'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
        from /mnt/campus/qlik_test/lib/qlik_api.rb:74:in `test'
        from (irb):1
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /mnt/campus/qlik_test/bin/rails:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'

It appeared when i use the restclient to execute the request,like this:
qlik_response = RestClient::Request.execute(:method => :post,
                                                :url => 'https://qv:4243/qps/ticket?Xrfkey=0123456789abcdef',
                                                :payload => {'UserId' => 'user1', 'UserDirectory' => 'qv', 'Attributes' => []},
                                                :headers => {'X-Qlik-Xrfkey' => '0123456789abcdef'},
                                                :verify_ssl => true,
                                                # :ssl_ca_path => '/etc/ssl/certs/',
                                                :ssl_ca_file => 'pem/10.11.10.140/client.pem',
                                                # :ssl_client_cert => OpenSSL::X509::Certificate.new(File.read('pem/10.11.10.140/client.pem')),
                                                :ssl_client_key => OpenSSL::PKey::RSA.new(File.read('pem/10.11.10.140/client_key.pem')),
                                                :content_type => :json)

but when i use the curl tool, it works well, like this:
curl -v -X POST "https://qv:4243/qps/ticket?Xrfkey=0123456789abcdef" --cert /mnt/campus/qlik_test/pem/10.11.10.140/client.pem --key /mnt/campus/qlik_test/pem/10.11.10.140/client_key.pem --header "x-qlik-xrfkey:0123456789abcdef" -d'{"UserDirectory":"qv","UserId":"user1"}' -H "Content-Type: application/json"

I tried this [issue](https://github.com/rest-client/rest-client/issues/288), but it doesn't work for me.

Any help is appreciated!

**Comment by zhanjianmin** [comment]
qlik_response = RestClient::Request.execute(:method => :post,
:url => 'https://qv:4243/qps/ticket?Xrfkey=0123456789abcdef',
:payload => {'UserId' => 'user1', 'UserDirectory' => 'qv', 'Attributes' => []}.to_json,
:headers => {'X-Qlik-Xrfkey' => '0123456789abcdef','Content-Type' => 'application/json'},
_**:verify_ssl => OpenSSL::SSL::VERIFY_NONE**_,
# :ssl_ca_path => '/etc/ssl/certs/',
# :ssl_ca_file => 'pem/10.11.10.140/client.pem',
:ssl_client_cert => OpenSSL::X509::Certificate.new(File.read('pem/10.11.10.140/client.pem')),
:ssl_client_key => OpenSSL::PKey::RSA.new(File.read('pem/10.11.10.140/client_key.pem'))
)

I use this parameters to request, and it work form me. But ignore the ssl verify is not a secure solution, is there any better suggestion?

**Comment by shintre** [comment]
I agree with @zhanjianmin, ignoring :verify_ssl => OpenSSL::SSL::VERIFY_NONE is not secure. Any other options?
