### ISSUE TITLE
warning: Overriding "Content-Type" header "application/x-www-form-urlencoded" with "application/x-www-form-urlencoded" due to payload

### ISSUE THREAD

**Issue by redbar0n** [rest-client/rest-client#577]
If a header has already been set _correctly_ in the post request (i.e. it matches the payload):

    RestClient.post url, { :u => u :pw => pw }, { :content_type => 'application/x-www-form-urlencoded' }

Then RestClient will disregard it, and merely give:

    warning: Overriding "Content-Type" header "application/x-www-form-urlencoded" with "application/x-www-form-urlencoded" due to payload

because RestClient only checks if the `headers.include?(key)`, and not if the contents of that key matches the header derived from the payload:
https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb#L376

RestClient should rather do something like

    if headers.include?(key) && headers[key] != val

**Comment by redbar0n** [comment]
Submitted a PR: https://github.com/rest-client/rest-client/pull/578

**Comment by cleanshavenalex** [comment]
Issue is not present in 2.0.0

**Comment by redbar0n** [comment]
It's present for me, in 2.0.1, which I always had

**Comment by ab** [comment]
Released in 2.0.2. Thanks!

**Comment by redbar0n** [comment]
Verified that issue is gone in 2.0.2. :-) Thanks for the release!
