### ISSUE TITLE
SSL Certificate pinning

### ISSUE THREAD

**Issue by BirknerAlex** [rest-client/rest-client#579]
Hello,

is it possible to pin a self signed SSL certificate? We using a external API and this API has a self signed certificate. The API provider can't change it to a valid certificate. We don't want to disable the SSL verification for this API call because it contains secret information. Disabling the verification is against our company security guidelines.

So what can I do?

I've been trying to solve it like this:
```ruby
result = RestClient::Request.execute({
   method: :get,
   url: "https://specialAPI",
   ssl_ca_file: File.read(File.join(Rails.root, 'certificates', 'api.pem')),
   verify_ssl: OpenSSL::SSL::VERIFY_PEER,
   timeout: 5,
})
```

But I still get this error message:
```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed: 
```

I think there is a Ruby OpenSSL option for this called "ssl_cert_file" but I think this option will be dropped from your library.

Regards,
Alexander

**Comment by ab** [comment]
`ssl_ca_file` should be a file path, not the file contents.

So from your example it should be:

    ssl_ca_file: File.join(Rails.root, 'certificates', 'api.pem'),

You can also use `ssl_verify_callback` to pass a function that implements whatever verification method you would like.
