### ISSUE TITLE
Issue with ouput that look like an HTML tag. Starts with '<'

### ISSUE THREAD

**Issue by cgte** [rest-client/rest-client#581]
Having the following displayed in response body preview tab : 
`
{
  "a": "<blablabla>"
}
`

the higlight tab displays : 

`    {
        "a": ""
    }`

A way to reproduce with python : 
get in a python 2 virtualenv then
pip install bottle

copy paste the following code [server.txt](https://github.com/rest-client/rest-client/files/834267/server.txt) and run `python server.txt` (sorry github does not allow attaching python file)

then use restclient to "get" : http://localhost:8080/ and http://localhost:8080/ex2 http://localhost:8080/1

You should experiment the same difference.

The 'bug' came to me since an api was improperly returning '<colander.null>' string, instead of dropping it.

**Comment by ab** [comment]
What is the response body preview tab? This doesn't sound like it has anything to do with rest-client. Feel free to reopen with more information.
