### ISSUE TITLE
Handle array parameter values

### ISSUE THREAD

**Issue by mperham** [rest-client/rest-client#59]
RestClient does not handle parameter values that are Arrays.  Typically this translates into a query parameter that looks like this:

    :q => [1,2,3]

into this:

    ?q=1&q=2&q=3

Specifically this patch does it (request.rb line 75):

          query_string = get_params.collect do |k, v|
            if v.is_a?(Array)
              v.map do |x|
                "#{k.to_s}=#{CGI::escape(x.to_s)}" 
              end.join('&')
            else
              "#{k.to_s}=#{CGI::escape(v.to_s)}" 
            end
          end.join('&')

**Comment by varunsrin** [comment]
+1

**Comment by patrickespake** [comment]
+1

**Comment by vitormm** [comment]
+1

**Comment by sergioazevedo** [comment]
+1

**Comment by XaMuT** [comment]
+1

**Comment by jiggneshhgohel** [comment]
+1

**Comment by draxxxeus** [comment]
+1

**Comment by mikevm** [comment]
> The brackets are a Rails convention for submitting array values via form post. 

so is it not possible to use this gem when the endpoint is a non-rails app?  i don't wish to have `[]` appended to each repeated parameter, as the endpoint i am using doesn't accept this format.

**Comment by taher435** [comment]
+1

**Comment by thousandsofthem** [comment]
+1

**Comment by galeng** [comment]
+1

**Comment by bstopp** [comment]
+1 Seriously, this is _still_ not fixed?

**Comment by kamalptw** [comment]
+1

**Comment by hq-mobile** [comment]
+1, wish I'd have known about this before getting 4 weeks into development depending on this gem.

**Comment by nbulaj** [comment]
+1 the same problem for 1.8.0

**Comment by CodingAnarchy** [comment]
Still seeing this issue in 2.0.2.
