### ISSUE TITLE
Get response body of 400

### ISSUE THREAD

**Issue by Herz3h** [rest-client/rest-client#592]
Hello,

I'd like to read to response body of a request. So in the code i do

```
begin
  Restclient.execute(...)
rescue RestClient::ExceptionWithResponse => e
  e.response.body # i only get a string message
end
```

How do i get access to the json body ?

**Comment by ab** [comment]
Do you mean how do you parse a string as JSON? i.e. `JSON.parse(body)`?

**Comment by Herz3h** [comment]
No i mean i dont have the json i expect as a response, instead i get a string in the body. This only happens when i return 400 error from web API serveur (ASP.net)

**Comment by ab** [comment]
I'm not sure I understand; HTTP as a protocol only transmits strings. You might interpret a string response as JSON and parse it with something like `JSON.parse(body)` which will deserialize the JSON into ruby objects, but the server is always actually transmitting a string.

Maybe an example showing what you expect to happen would help?

**Comment by Herz3h** [comment]
The thing is when i write : 

**e.response** it woudln't show the response body of the response. But then i figured it was ASP Web Api issue, that it removed the body and only kept status message. So i did this in ASP Web Api : 

`Response.TrySkipIisCustomErrors = true;`

So the problem was from the webserver i was contacting and not rest-client.

So this is really not an issue, thanks for trying to help @ab :)
