### ISSUE TITLE
Will restclient use CONNECT when talking to a https endpoint via a proxy?

### ISSUE THREAD

**Issue by ankitrg** [rest-client/rest-client#593]
I am trying to configure proxy with restclient and the endpoint that I am trying to access is `https`, the docs for the proxy says something like this:

> You can access HTTPS services via the HTTP proxy whilst still getting full SSL/TLS security. When you make a request via the proxy to an HTTPS endpoint your client should transparently issue a CONNECT request rather than a basic GET request.
On receipt of this CONNECT request the proxy will open a tunnel between your client and the endpoint, allowing your client to negotiate a standard SSL session with the endpoint. Once negotiated all traffic sent between your client and the endpoint will be encrypted as if you had connected directly with them.

So my doubt is will the restclient do this automatically? How can I go about doing this?

I am sorry if I am being naive. Thanks.

**Comment by ab** [comment]
Yes, rest-client uses Ruby Net::HTTP under the hood, which will automatically issue a `CONNECT` request for HTTPS over an HTTP proxy.

You can set this by setting the environment variable `https_proxy` or setting `RestClient.proxy`.

Testing this by running a fake local proxy:
```
$ nc -v -l 5000
Listening on [0.0.0.0] (family 0, port 5000)
```

```ruby
>> RestClient.proxy = 'http://localhost:5000'
>> RestClient.get('https://example.com/')
```

The netcat server will now show the `CONNECT` request

```
Connection from [127.0.0.1] port 5000 [tcp/*] accepted (family 2, sport 42916)
CONNECT example.com:443 HTTP/1.1
Host: example.com:443
```
