### ISSUE TITLE
RestClient::Resource timeout exception? 

### ISSUE THREAD

**Issue by NidhiArien** [rest-client/rest-client#596]
Hi, for unavoidable reasons, we are still using older version of restclient(1.7.3). 

I have to add a timeout feature for my rest calls which is doing a GET. 

This is the code roughly: 

   begin
       resource = RestClient::Resource.new(url, :timeout => 3)   
       response = resource.get        
    rescue => e
         Rails.logger.error "Exception in method xyz"
    end

From what I have understood so far restclient(1.7.3) when times out raises RestClient::RequestTimeout. This should be caught in my general resque. Is that correct? Please clarify.

**Comment by ab** [comment]
Yes, in rest-client 1.7.x you can pass `:open_timeout` to set a timeout on connecting and `:timeout` to set a timeout on reads.

Both will cause `RestClient::RequestTimeout` to be raised. This inherits from the main response/exception class, `RestClient::ExceptionWithResponse`.

The confusing part in rest-client 1.7.x is that this same exception will also be raised if a server returns a HTTP 408 "Request Timeout" response. The only way to tell the difference is to examine `.response` (nil versus response string object) or `.message` on the exception object.

http://httpbin.org/delay/5 also provides a decent way to test your timeout behavior.

http://httpbin.org/
