### ISSUE TITLE
No response retry to send request

### ISSUE THREAD

**Issue by DanielZhangQingLong** [rest-client/rest-client#605]
I've found restclient will retry to send request if dest server does not response. I wonder how to disable re-resending request to server. Thanks.

**Comment by ab** [comment]
I suspect you're running into the Net::HTTP built-in retries. Unfortunately, I don't think this is configurable in any way.

**Comment by ab** [comment]
Closing this since it isn't under rest-client's control, but feel free to reopen with more suggestions or information.

**Comment by ionutzp** [comment]
i think this is now configurable
https://github.com/mrkn/ruby/commit/439550a0692518bb2827ee178f2207d0687dc3c8
