### ISSUE TITLE
Replace "Master Shake" photo to remove Creative Commons Attribution-ShareAlike 2.0 license

### ISSUE THREAD

**Issue by robinbobbitt** [rest-client/rest-client#606]
Would you consider replacing the Master Shake photo with an image with friendlier terms, e.g. public domain? I understand the Creative Commons Attribution-ShareAlike license can be considered viral in nature, and swapping out this image would remove any current or future concerns. Thanks!

**Comment by ab** [comment]
Thanks for the suggestion!

**Comment by robinbobbitt** [comment]
Thank you!
