### ISSUE TITLE
Memory leak in ruby 2.4.0+

### ISSUE THREAD

**Issue by krzyzakk** [rest-client/rest-client#611]
Hello, I have encountered a memory leak while using RestClient to do a lot of get requests in ruby versions 2.4.0-2.4.1.

This can be recreated using:
```ruby
100000.times.each_slice(32) do |slice|
    slice.map { Thread.new { RestClient.get('echo.jsontest.com/key/value/one/two') } }.each(&:join) 
end
```

Whereas:
```ruby
100000.times.each_slice(32) do |slice|
    slice.map { Thread.new { Net::HTTP.get('echo.jsontest.com', '/key/value/one/two') } }.each(&:join) 
end
```
works just fine memory-wise.

My app fires even more get requests with bigger responses and after running for few seconds with RestClient the memory used goes to GBs. This does not happen in ruby versions below 2.4.0, specifically: 2.3.1-2.3.4.

**Comment by ab** [comment]
I can confirm that after just 10,000 rest-client requests, the MRI ruby 2.4.1 RSS grows to 314 MB, and virtual memory usage grows to 11.5 GB. Running the same test in MRI ruby 2.3.4 show RSS of 132 MB and VIRT of 2.1 GB.

I've made some progress in tracking this down, and signs are pointing to this being a bug in Ruby MRI.

With object allocation tracing enabled, ObjectSpace.memsize_of_all shows that Ruby is only tracking 27 MB of objects. And this number does not grow dramatically over time even as RSS grows. So the memory leak must be coming from allocated memory from a C extension or from an MRI bug.

Commenting out the call to `RestClient::Response.fix_encoding` in `response.rb` appears to stop the leak. It looks like this is triggered by `RestClient::Utils.cgi_parse_header` in `utils.rb`.

I have a sneaking suspicion that this is related to #523.

I'm working on a PR to replace this parser code with some more idiomatic Ruby that won't trigger the bug.

**Comment by ab** [comment]
Just in case it's useful in the future, here are some references I used in tracking down the leak:

- https://samsaffron.com/archive/2015/03/31/debugging-memory-leaks-in-ruby
- https://samsaffron.com/archive/2014/04/08/ruby-2-1-garbage-collection-ready-for-production
- https://samsaffron.com/archive/2013/11/22/demystifying-the-ruby-gc
- https://github.com/SamSaffron/memory_profiler
- http://www.be9.io/2015/09/21/memory-leak/
- https://thorstenball.com/blog/2014/03/12/watching-understanding-ruby-2.1-garbage-collector/
- https://stackoverflow.com/questions/32923610/why-doesnt-this-ruby-program-return-off-heap-memory-to-the-operating-system
- https://stackoverflow.com/questions/25429022/how-to-deal-with-ruby-2-1-2-memory-leaks
- http://holymonkey.com/how-to-find-and-fix-a-memory-leak-in-a-ruby-c-extension.html
- https://blog.codeship.com/debugging-a-memory-leak-on-heroku/

**Comment by SamSaffron** [comment]
reported this here: 

https://bugs.ruby-lang.org/issues/13772

I think it is to do with recycling stacks in ruby threads.

**Comment by cben** [comment]
#523 was on 2.3.  If it's the same leak then maybe https://bugs.ruby-lang.org/issues/13772 
 should be backported to 2.3 (currently marked 2.3 DONTNEED)?

**Comment by SamSaffron** [comment]
The memory leak and segfault are not the same issue. Mem leak is 2.4
specific

**Comment by bleedr** [comment]
Is there a workaround? I noticed this in a few scripts I wrote and it's crashing when memory is full. Doing a lot request and it accumulates pretty fast

**Comment by SamSaffron** [comment]
Either wait for ruby 2.4.2 or downgrade to 2.3.4

**Comment by bleedr** [comment]
Thanks, installing 2.3.4 on the Raspi right now!

**Comment by sodabrew** [comment]
MRI 2.4.2 is released with the necessary bugfix included!
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/
