### ISSUE TITLE
'fetch': key not found: :ciphers

### ISSUE THREAD

**Issue by maxiedaniels** [rest-client/rest-client#612]
I'm getting this error on Ruby 2.4.0. I've read about the issue on other github pages and people said the new version of rest-client fixes it, but I've updated to the latest rest-client and I'm experiencing the same issue..

**Comment by LRP500** [comment]
Got the same issue while using Sellsy API. I'm on rest-client v1.7.3

**Comment by ab** [comment]
This was fixed in rest-client 2.0.1. #573

**Comment by ab** [comment]
P.S. @maxiedaniels I just noticed you said you'd already upgraded to the latest version. Which version are you running?

`RestClient::Platform.default_user_agent` will give the most useful version info.

**Comment by maxiedaniels** [comment]
Nevermind - this can be closed. It turns out the gem I was using, rspotify, is forcing the use of the old rest-client even though I have the new rest-client installed. That's what is happening... but that's on rspotify's end now to update. Thanks!

**Comment by ConAllen** [comment]
Hey guys im trying to create a charge using the stripe API and im having the same problem.

"KeyError in OrdersController#create
key not found: :ciphers"

can anyone please help me resolve this? 

many thanks

**Comment by ab** [comment]
@ConAllen What version of rest-client are you using?

**Comment by ConAllen** [comment]
@ab  I hadnt heard of rest client before. im unaware of what version i had.

I just tried to install it again using the information on this link in my terminal
http://macappstore.org/wiztoolsorg-restclient/

and it failed

now i cant connect to my server - have you any idea how to help. total nightmare.

**Comment by ConAllen** [comment]
@ab my server is cancelling and the terminal error is as follows. 

"/Users/ConAllen/.rvm/gems/ruby-2.4.0/gems/devise-4.2.0/lib/devise/rails/routes.rb:498:in `raise_no_secret_key': Devise.secret_key was not set. Please add the following to your Devise initializer: (RuntimeError)

  config.secret_key = 'f0d7ac1fbfd53a8d2f8db2554030d1c3fe18cd9c5167e9f549d48f00a875414b178d4a61dc7ba736a2f419dd06b654c010c9faa07f3c3d2c8e32aa764f3cabb3'

Please ensure you restarted your application after installing Devise or setting the key."

many thanks for any help you can offer.
Con

**Comment by ConAllen** [comment]
@ab hey can you tell me how to check what rest-client i have? and how to update it? many thanks

**Comment by ab** [comment]
@ConAllen This page is the issue tracker for rest-client, a Ruby HTTP library. If "RestClient" does not appear in your error logs, it does not sound like you are using rest-client. Older versions of the Stripe API library for Ruby used rest-client, but the latest versions do not. You might try reaching out to Stripe support if you're having difficulty integrating. https://support.stripe.com/

**Comment by ConAllen** [comment]
Hi Andy,

thanks a mill for all your help. kind Regards
Con

**Comment by bioffe01** [comment]
For those who still want to use old rest-client gems here is oneliner 
`OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ciphers]=OpenSSL::SSL::SSLContext.new.ciphers;`

enjoy!
