### ISSUE TITLE
RestClient::RequestFailed does not wrap all kinds of request failures

### ISSUE THREAD

**Issue by perlun** [rest-client/rest-client#618]
For example, `Errno::ECONNREFUSED` (this is what happened to me).

Would it make sense to make our error handling a bit more robust and catch errors like that also? There are probably others as well:

- ECONNRESET
- maybe others?

In general, thanks for a nice gem though! 👍

**Comment by ab** [comment]
Yeah this is a known wart. :confused:  In general rest-client doesn't handle any exceptions for you except for converting `OpenSSL::SSL::SSLError` to `RestClient::SSLCertificateNotVerified`.

https://github.com/rest-client/rest-client/issues/286
