### ISSUE TITLE
right place for helper function?

### ISSUE THREAD

**Issue by tbhi** [rest-client/rest-client#620]
I often use the function below and wonder if it would make sense to include it in rest-client (perhaps RestClient::Resource.new_from_gem_configuration)?

```
def restclient_from_gem_configuration(url)
  client_pem = File.read(Gem.configuration.ssl_client_cert)
  RestClient::Resource.new(
    url,
    :ssl_client_cert => OpenSSL::X509::Certificate.new(client_pem),
    :ssl_client_key  => OpenSSL::PKey::RSA.new(client_pem),
    :ssl_ca_file     => Gem.configuration.ssl_ca_cert,
  )
end
```

**Comment by ab** [comment]
What is `Gem.configuration`? At first glance, this doesn't look like something that belongs in rest-client itself.

**Comment by stan3** [comment]
It's one of these, http://docs.seattlerb.org/rubygems/Gem/ConfigFile.html which always seems to be available on the Gem module, http://docs.seattlerb.org/rubygems/Gem.html.  Perhaps a separate gem would be better.
