### ISSUE TITLE
local storage support

### ISSUE THREAD

**Issue by akostadinov** [rest-client/rest-client#622]
Would be nice to support local storage [1]. Or would this kind of feature would not be considered anytime soon?

[1] https://developer.mozilla.org/en/docs/Web/API/Window/localStorage

**Comment by ab** [comment]
What would supporting local storage mean in the context of rest-client? It seems like that's only applicable for a browser running javascript.

**Comment by akostadinov** [comment]
Yes, I was wondering whether any level of js would be supported. Like in some headless browsers. I'm not telling that's necessary. Just asking.

**Comment by ab** [comment]
Thanks, rest-client doesn't implement any bit of JavaScript, so this seems well out of scope.
