### ISSUE TITLE
Request.execute mutates headers hash

### ISSUE THREAD

**Issue by ThePeiggy** [rest-client/rest-client#623]
I attempted to pass an immutable hash constant to the `headers` param, but it seems `execute` is actually attempting to mutate it. I think this is an undesirable behaviour. A copy of the `headers` param should be made.

**Comment by ab** [comment]
What version of rest-client are you running? This is a known issue in historic versions of rest-client, but it should be fixed in >= 2.0.

https://github.com/rest-client/rest-client/commit/1e85af475f146ce2f6b5fad3ae233793c0c3ebc9
