### ISSUE TITLE
Request: before_execution_proc can't really customize args

### ISSUE THREAD

**Issue by alb-i986** [rest-client/rest-client#625]
I've found this issue while trying find a way to set verify_ssl mode to false once and for all the requests.
[This SO answer](https://stackoverflow.com/a/39792499/1797282) suggests to use a `before_execution_proc` like this:

```
RestClient.add_before_execution_proc do |req, params|
  params[:verify_ssl] = false
end
```

But unfortunately it doesn't work, as I point out in a [comment below](
https://stackoverflow.com/questions/39791621/how-can-i-wrap-every-request-with-restclient-to-use-verify-ssl-false#comment78924290_39792499).

While investigating on why it doesn't work I've found this bug.
The thing is that `args`, which is passed to each `before_execution_proc `, is processed only once in the constructor (see [around here](https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb#L85)), and never accessed again. Therefore, any customization to any of the args by a `before_execution_proc` will never be read. Thus, `before_execution_proc` can't really customize args.

Also, the before_procs [are executed pretty late in the method `#transmit`](https://github.com/rest-client/rest-client/blob/6beead019b9971f9576e78f78e140a377b3d6d3d/lib/restclient/request.rb#L709) (for instance, after setting the SSL opts in the HTTP connection object) => their power is limited.

**Comment by iamliamc** [comment]
I'll just note that i've been able to reproduce @alb-i986 results here. 

I was trying to utilize this feature so that _all_ requests made from a particular application to another application contained a specific param.  

```
RestClient.add_before_execution_proc do |req, params|
  if params[:url].include?("?")
    params[:url] += "&always=1"
  else
    params[:url] += "?always=1"
  end
end
```
After I make my RestClient request, I go to the application being called and it receives the get request without the _always_ param.

**Comment by ab** [comment]
Thanks for the issue. I would caution against using `before_execution_proc` for much of anything. It's a relic from very early in rest-client's design, and essentially represents some glorified monkey patching.

If you want common RestClient calls to use the same parameters in some way, I would create a subclass of RestClient::Request and override the relevant methods, or create a wrapper class or method that does what you're looking for.

Regardless, disabling SSL verification is a dangerous thing to do. You may as well not use HTTPS at all if you're not going to verify certificates.

**Comment by alb-i986** [comment]
Hey @ab,
it's been a while, but thanks for looking into this! :)
