### ISSUE TITLE
[feature] Provide a constant `RestClient.ssl_opts`

### ISSUE THREAD

**Issue by alb-i986** [rest-client/rest-client#626]
Just like `RestClient.proxy` allows to set the proxy once and for all the requests, it would be useful to have a similar `RestClient.verify_ssl` to set verify_ssl once and for all.
`RestClient::Request` should allow to override that value through the parameter of the constructor, as it does for the proxy.

**Comment by alb-i986** [comment]
Or, even better, more generic: `RestClient.ssl_opts`.

**Comment by tarraschk** [comment]
Hello,

you can already do that for a resource.

```ruby
# Code
require 'rest-client'
resource = RestClient::Resource.new('https://some/resource', verify_ssl: false)
resource['/'].get
```

Every request done from the resource will share the parameters defined in the resource, and will as a result share the verify_ssl parameter.

**Comment by ab** [comment]
We're trying to get away from global state like `RestClient.proxy`, so I wouldn't want to do something like that. For SSL in particular, such an option is particularly dangerous. You may as well not use HTTPS at all if you're not going to verify certificates.
