### ISSUE TITLE
rest-client doesnt handle '#' in url

### ISSUE THREAD

**Issue by uherbst** [rest-client/rest-client#627]
Hi,

'require rest-client'
myurl = "http://xxx/this/is/an/URL/#xx/more"
Response = RestClient.get myurl

Does not work.

Tcpdump shows: The request ist just made to
http://xxx/this/is/an/URL/

any ideas how to solve that ?

**Comment by ab** [comment]
RestClient is behaving the same way your browser would. `#` has a special meaning in a URL because it marks the fragment identifier: https://en.wikipedia.org/wiki/Fragment_identifier.
