### ISSUE TITLE
verify_ssl: false doesn't work as expected

### ISSUE THREAD

**Issue by xam7247** [rest-client/rest-client#628]
Hi, 

My app uses HTTPS with self-signed certs on a demo box (only for limited purposes). Hence I wish to skip HTTPS / SSL without any validation..

I tried setting verify_ssl: false as:
`RestClient::Request.execute(method: get, url: <some_https_url>, headers: headers, verify_ssl: false)
`

This still fails with 
```
OpenSSL::SSL::SSLError:
       SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
     # ./vendor/cache/rest-client-2.0.2/lib/restclient/request.rb:714:in `transmit'
     # ./vendor/cache/rest-client-2.0.2/lib/restclient/request.rb:146:in `execute'
     # ./vendor/cache/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
```

Stepping through the code, it seems `RestClient::Request.execute` internally calls `RestClient::Request.transmit`, which evaluates use_ssl on the basis of HTTPS URI, hence setting 
```
net.use_ssl == true
net.verify_mode == 0
```

With this, (I think) the request still tries to validate SSL (probably CA certs, if not self-signed cert?). 
Manually setting `net.use_ssl = false` in unpacked gem ignores SSL validation completely and works as expected. 

Maybe 
`net.use_ssl = uri.is_a?(URI::HTTPS) `
should rather be
`net.use_ssl = uri.is_a?(URI::HTTPS) unless (verify_ssl == false) `

This is currently blocking us, and we are unable to use RestClient, since we cannot override the use_ssl property externally too. Any recommendation to solve this ? 

Thanks in advance.

**Comment by ab** [comment]
"unknown protocol" is an error message coming from some SSL communication or protocol failure, not SSL certificate verification.

Anytime you have an `https://` URL, you are using SSL. You can choose not to verify certificates (with `verify_ssl: false`), but you are still using HTTPS.

If you don't want to use HTTPS, pass an `http://` URL.

**Comment by xam7247** [comment]
@ab: why was this closed ?

I explicitly mentioned it is using HTTPS, but I am choosing to not verify certificates. But` verify_ssl: false` is not working due to a bug in the code. 

Please read the issue again. Not sure how to re-open this.

**Comment by dstull** [comment]
@xam7247 did you ever get around this?  I have similar issue where I can't update my OS ssl (which is causing the issue -exact same message as yours) - I have no control over it

**Comment by xam7247** [comment]
@dstull : Nope, we ended up not using SSL on local, and only on environments with complete SSL implemented. If its blocking you, you could unpack the gem and use a local fix (note: this would need to be done each time you plan to update rest-client gem)

**Comment by ctrlaltdylan** [comment]
I have to bump this as well. I've been struggling with this bug for the past couple of days. I've forked the repo and the tests pass and I even added an integration test to call a site with a self-signed cert just to _know_ for a fact that passing `verify_ssl: false` works.

*But* it continues to plague us in our docker environment. We use `rest-client` as the backbone for an API client. When testing outside of the docker network the `verify-ssl: false` works as expected. But within the network the `verify_ssl: false` appears to have no effect whatsoever.

**Comment by davidvasandani** [comment]
`verify_ssl: OpenSSL::SSL::VERIFY_NONE` resolved the issue for us.
