### ISSUE TITLE
rest-client depends on http-accept

### ISSUE THREAD

**Issue by ioquatix** [rest-client/rest-client#629]
Hello.

I'm the developer of `http-accept` and I'd like to open a dialogue regarding the project. I see it's currently in your latest rc.

I don't really have much to add, but it would be good to establish a point of contact for both projects.

**Comment by ab** [comment]
Hello. Thanks for creating `http-accept`!

rest-client has barely been maintained for the past two years, but I'm planning to look for a couple of new maintainers in the near future.
