### ISSUE TITLE
warning: Overriding "Content-Type" header "application/json" with "application/x-www-form-urlencoded" due to payload

### ISSUE THREAD

**Issue by cryst10** [rest-client/rest-client#635]
### version: rest-client (2.0.2 x64-mingw32)

I have seen that this issue was supposed to be fixed in [#578](https://github.com/rest-client/rest-client/pull/578) for **version 2.0.2**

But I am getting this issue in my case while test my client.

```ruby
RestClient::Request.execute(:method => m, :url => u, :payload =>{'hello' => 'world'}, :headers => {:content_type=>"application/json"})
```

and get the following error:
```
warning: Overriding "Content-Type" header "application/json" with "application/x-www-form-urlencoded" due to payload
```

**Comment by cryst10** [comment]
actually JSON serialising solves the problem

**Comment by fangzongwu** [comment]
JSON serialising ? how to do ?

**Comment by robbmanes** [comment]
> JSON serialising ? how to do ?

```
require 'json'
json_obj = JSON.generate({"hello" => "world"})
RestClient::Request.execute(:method => m, :url => u, :payload =>json_obj, :headers => {:content_type=>"application/json"})
```
You can just make your hashes into a JSON object with the `JSON.generate {:my => "hash"}` method.  That will allow it to POSt as application/json content.

**Comment by shahzeb1** [comment]
Even while using JSON as the payload, the content type is still being set to `x-www-form-urlencoded`

```
@options = JSON.generate({"isActivate" => true})
RestClient.put("#{@base_uri}/surveys/#{surveyId}", payload=@options, headers=@auth)
```

**Comment by jessenovotny** [comment]
@shahzeb1 what is the value of `@auth`? I also don't think it's necessary to use `payload=` or `headers=`. All of my requests just look like `RestClient.put(url, payload, headers)`
