### ISSUE TITLE
How to Explicity Set an HTTP header Value

### ISSUE THREAD

**Issue by ninp0** [rest-client/rest-client#641]
Greetings,

I'm running into an issue where a REST API is expecting a case-sensitive UserToken: <key_value> in an HTTP header (despite case insensitive HTTP RFCs), however, I can't seem to determine how to explicitly set the HTTP header to UserToken w/o it getting converted by rest-client:

```
rest_response = rest_client.execute(
  method: :post,
  url: "#{base_url}/api/request,
  verify_ssl: false,
  headers: {
    content_type: 'application/json',
    user_token: '<key value>'
  }
) {|response, request, result| response } # Don't raise exception for unfavorable HTTP responses
```
```
user_token: '<key value>' 
```

evaluates to **_User-Token_** in the actual HTTP request.

```
'UserToken' => '<key value>'
```

evaluates to **_Usertoken_** in the actual HTTP request.

How do I get **_UserToken_** in the actual HTTP request?

I know the REST API _should_ work but it simply doesn't and it's something they're unwilling to change.  Seems to me if rest-client supports setting explicit header keys in HTTP requests, it wouldn't violate RFCs (at least from this gem's perspective) and still allow us to interact w/ poorly conforming servers.  Thoughts?

Thanks in advance for your help!

**Comment by tarraschk** [comment]
Hello

Rest-Client does support explicit header keys.

Look at this syntax.

```ruby
# Code
require 'rest-client'
resource = RestClient::Resource.new('http://some/resource', :headers => { "UserToken" => 1 })
RestClient.log = 'stdout'
resource['/'].get

# Output
RestClient.get "http://some/resource/", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "User-Agent"=>"rest-client/2.0.2 (darwin16.5.0 x86_64) ruby/2.5.1p57", "UserToken"=>"1"
```

**Comment by ninp0** [comment]
ok thanks!
