### ISSUE TITLE
How to use the token based X-Authentication using this gem??

### ISSUE THREAD

**Issue by kandukurivarun** [rest-client/rest-client#648]
I want to pass the access-token to my POST request. Endpoint uses X-Authentication in order to authenticate the requests. How can i pass the token to my request?

 

I am getting the following error:
`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

I am using the https endpoint with X-Authentication header without SSL certs(Insecure).

**Comment by tarraschk** [comment]
This problem does not come from the X-Authentication header, but from the fact that the SSL cert is self-signed or can't be verified.

You can use the parameter `verify_ssl: false` in your request to specify that it should ignore the SSL check.

Look at this issue: https://github.com/rest-client/rest-client/issues/288
