### ISSUE TITLE
Uri encode with spaces, bug

### ISSUE THREAD

**Issue by nPaul** [rest-client/rest-client#659]
How to set up RestClient so that the spaces are converted to "%20" instead of '+'
Because odata service not undestand if uri have symbol '+', give an error that of operation +(plus) not available.

**Comment by KorranForce** [comment]
You need to manually encode query string and concatenate it with url - not send it to RestClient as value of params field in headers. Or use this dirty monkey patch:
```
module RestClient
	module Utils
		def self.encode_as_www_form(object)
			flatten_params(object, true).map {|k, v| v.nil? ? k : "#{k}=#{v}"}.join('&')
		end
		def self.encode_query_string(object)
			URI.escape(flatten_params(object, false).map {|k, v| v.nil? ? k : "#{k}=#{v}"}.join('&'))
		end
	end
	module Payload
		class UrlEncoded < Base
			def build_stream(params = nil)
				@stream = StringIO.new(Utils.encode_as_www_form(params))
				@stream.seek(0)
			end
		end
	end
end
```
