### ISSUE TITLE
v2.0.2 has a bug in log_request

### ISSUE THREAD

**Issue by FX-HAO** [rest-client/rest-client#664]
When enabling logging, I got `NoMethodError (undefined method > for nil:NilClass)` in `RestClient::Payload::Base#short_inspect`.

https://github.com/rest-client/rest-client/blob/4ba9f7ee6374ec25abb870f769059b162ad7642a/lib/restclient/payload.rb#L88-L90

It seems that the issue has been fixed at v2.1.x

**Comment by ab** [comment]
Yeah, this is a known issue with `#size` not always being implemented. It ought to be fixed in 2.1.0, which was just released.
