### ISSUE TITLE
Undefined method delete_if in Event url parameter value contains both https:// and port 443

### ISSUE THREAD

**Issue by ninp0** [rest-client/rest-client#666]
Small error - more of an fyi...had to write a condition on my end to get around it:

```
url = 'https://somedomain:443'
rest_client = RestClient::Request
response = rest_client.execute(
  method: :post,
  url: "#{base_dd_api_uri}/users",
  verify_ssl: false
)

NoMethodError: undefined method `delete_if' for #<String:0x00005638a08e51c8>

Did you mean?  delete

               delete!

from /usr/local/rvm/gems/ruby-2.5.1@csi/gems/rest-client-2.0.2/lib/restclient/request.rb:186:in `process_url_params'
```

**Comment by ninp0** [comment]
Apologies - this has to do w/ headers...disregard.

**Comment by mujohn26** [comment]
> Apologies - this has to do w/ headers...disregard.

Hi @ninp0 , was this fixed? cause I'm still facing this issue with Rest client.

**Comment by ninp0** [comment]
Hi @mujohn26,

To my knowledge the missing delete_if method wasn't fixed, however, there's good news.  

Based on my last comment, in my particular case it appears I was able to work around this issue by adding a missing HTTP header.  Have you attempted to add a content_type header key in the headers hash?

For example,

```
            response = rest_client.execute(
              method: :post,
              url: "#{base_dd_api_uri}/users",
              headers: {
                content_type: 'application/json; charset=UTF-8',
                authorization: "Bearer: #{token}"
              },
              payload: http_body.to_json,
              verify_ssl: false,
              timeout: request_timeout,
              open_timeout: request_timeout
            )
```

That all aside, there's probably still something else wrong when capturing the exception (i.e. undefined method delete_if).  Hope that helps.
