### ISSUE TITLE
PATCH on a url returns invalid JSON PATCh error

### ISSUE THREAD

**Issue by vishalpatel1587** [rest-client/rest-client#678]
Ran a PATCH on an API
The following three headers were included.
Authorization: Bearer aqMnvJCTuyEYV0NxeQXfdDFe433DFfse34piCcAXv0J25Q
Accept: application/json
Content-Type: application/merge-patch+json

The body is a json body.

This however returns a 500 error saying Invalid JSON patch.

**Comment by ab** [comment]
This doesn't sound like a bug with rest-client, but feel free to reopen with more information if it is.
