### ISSUE TITLE
A way to use proxy inside `Resource`

### ISSUE THREAD

**Issue by empeje** [rest-client/rest-client#679]
I need to create an API call with a specific proxy for each of API client (payment, search, etc) right now it is not possible if I use `Resource`.

**Comment by ab** [comment]
The `Resource` API isn't super well supported. I'd recommend wrapping `RestClient::Request.execute` in some methods of your own if you want to reduce code duplication. Pull requests are also welcome.

**Comment by empeje** [comment]
Thanks @ab
