### ISSUE TITLE
ALT+E wont work on uk keyboard when this plugin is present

### ISSUE THREAD

**Issue by clperez** [rest-client/rest-client#680]
Hi:

I usually use ALT+E to type "é" character on a UK keyboard. 

My keybindings contains the following: 
   `Defaults: { "key": "ctrl+alt+e",            "command": "rest-client.switch-environment" },`

No mention to "alt+e" in my user keybindings file.

When I press right ALT+E the following dialog is displayed: 

![image](https://user-images.githubusercontent.com/1532943/46275732-df0f1600-c555-11e8-8757-27b8ca956277.png)

I tried adding the following to my users keybindings:
   `Defaults: { "key": "alt+e",            "command": "" },`

But the behaviour persists.

I would expect to be able to type ALT+A|E|I|O|U to type á,é,í,ó,ú.

**Comment by ab** [comment]
Your issue doesn't appear to be related to Ruby rest-client. This repository is the home of the Ruby rest-client gem. It is unrelated to any kind of GUI environment.
