### ISSUE TITLE
Per-request logging does not working

### ISSUE THREAD

**Issue by khataev** [rest-client/rest-client#685]
I'm trying something like this:

```       
RestClient::Resource
          .new(
            url,
            headers:          headers,
            ssl_client_cert:  client_cert,
            ssl_client_key:   client_key,
            verify_ssl:       OpenSSL::SSL::VERIFY_NONE,
            log:              Logger.new(Rails.root.join('log', 'restclient.log'))
          ).post(payload.to_json)
```

and file remains empty. Logging works only if I set log destination globally

`RestClient.log = Logger.new(Rails.root.join('log', 'restclient.log'))`

Bug?

**Comment by obfuscoder** [comment]
Any updates on this issue?

**Comment by ab** [comment]
What version of rest-client are you using? The per-request log was not added until rest-client >= 2.1.0.rc1. The final 2.1.0 was only just released today. #538

**Comment by ab** [comment]
I'm closing this, since I'm betting the issue was a divergence between the README on master and the behavior in the old stable 2.0.2 release which didn't include this functionality, but feel free to reopen if this is still not working on rest-client 2.1.0.
