### ISSUE TITLE
Can't rescue Net::HTTPFatalError with RestClient::ExceptionWithResponse

### ISSUE THREAD

**Issue by rmonteiro89** [rest-client/rest-client#690]
Hi,

I thought RestClient::ExceptionWithResponse would rescue any exception Net::HTTP raised, and then i had a surprise when it didn't rescue Net::HTTPFatalError.

Is there a reason to not rescue this specific exception? Are there others? What are good ways to handle it in the case I need to rescue this exception? Is there any other abstraction class to handle the low level exceptions related to http?

The specific error I got was:
`Net::HTTPFatalError: 502 "Bad Gateway"`

Example:
```ruby
def error
  raise Net::HTTPFatalError.new('teste', nil)
rescue RestClient::ExceptionWithResponse => err
  puts 'ola'
end
```

Thank you so much for any help! =)

Below is the stacktrace from Rollbar:
```
{
          "is_project_frame": false, 
          "method": "execute", 
          "lineno": 52, 
          "filename": "/app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb"
        }, 
        {
          "is_project_frame": false, 
          "method": "execute", 
          "lineno": 145, 
          "filename": "/app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb"
        }, 
        {
          "is_project_frame": false, 
          "method": "transmit", 
          "lineno": 715, 
          "filename": "/app/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb"
        }, 
        {
          "is_project_frame": false, 
          "method": "start", 
          "lineno": 909, 
          "filename": "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb"
        }, 
        {
          "is_project_frame": false, 
          "method": "do_start", 
          "lineno": 920, 
          "filename": "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb"
        }, 
        {
          "is_project_frame": false, 
          "method": "connect", 
          "lineno": 958, 
          "filename": "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb"
        }, 
        {
          "is_project_frame": false, 
          "method": "value", 
          "lineno": 131, 
          "filename": "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb"
        }, 
        {
          "is_project_frame": false, 
          "method": "error!", 
          "lineno": 122, 
          "filename": "/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb"
        }
      ], 
      "exception": {
        "message": "502 \"Bad Gateway\"", 
        "class": "Net::HTTPFatalError"
      }, 
      "extra": {}
    }
  }
```

**Comment by ab** [comment]
Unfortunately, there are a large number of low-level exceptions that will not be wrapped by RestClient. In fact, the only exceptions that are wrapped and reraised are timeout errors, connection prematurely closed errors, and SSL verification failures. Everything else will be passed through as-is, including various errors like SocketErrors and Errno::ECONNREFUSED.

Are you using an HTTP proxy? I believe that those exceptions are not wrapped by rest-client for backwards compatibility. You also wouldn't want to confuse an HTTP 502 from the proxy with an HTTP 502 from the destination server.

It's definitely on our radar to bring more sanity to the exception hierarchy and to either wrap _all_ exceptions or _no_ exceptions, to the extent possible. But this would have to wait for a new major version.

https://github.com/rest-client/rest-client/issues/286

**Comment by ab** [comment]
Here's the issue I filed specifically for HTTP proxy exceptions: https://github.com/rest-client/rest-client/issues/675
