### ISSUE TITLE
how to show rest-client request body for bigger requests

### ISSUE THREAD

**Issue by jaluke** [rest-client/rest-client#694]
Is there configuration which cuts the request payload logging in rest-client? It only summaries the size e.g. "565 byte(s) length" and does not show the request body.

I noticed that when using rest-client logging with How to debug/display request sent using RestClient is does not show the request payload for "bigger" requests. For smaller bodies the body is logged as expected.

```
[RestClient] RestClient.post "https://www.example.com/payments", 565
byte(s) length, "Accept"=>"application/json",
"Accept-Encoding"=>"gzip, deflate", "Content-Length"=>"565",
"Content-Type"=>"application/json"
```

I am currently using rest-client (2.0.2) on rails 4.2.7

Refs to stackoverflow:
https://stackoverflow.com/questions/48262021/missing-setting-for-showing-rest-client-request-body-for-bigger-requests

**Comment by ab** [comment]
There's no configuration option for this, but you could subclass RestClient::Request and override the `log_request` method to do whatever logging you wanted including outputting the entire payload.
