### ISSUE TITLE
pass cert file and password to make get request in ruby

### ISSUE THREAD

**Issue by sshriv14** [rest-client/rest-client#703]
Hi,

I have a curl command to get data from an endpoint --
```
curl \
 --cert "test.pem" \
 --pass "test" \
 "https://api.test.test.com/api/v1/test"
```

I am able to fetch the data from this.

But I want to do the same using rest-client. I have tried following without success :

```
require 'rest-client'
require 'json'
require 'net/http'

# cert =  OpenSSL::PKey::RSA.new(File.read("test.pem"), "test")
url = "https://api.test.test.com/api/v1/test"
pass = "test"
pem_path = "/Users/test/Desktop/test.pem"
# reply = RestClient.get(url, ssl_options={:ssl_ca_file => pem_path}, params={:pass => pass})
reply = RestClient::Request.execute(method: :get, url: url,
                          ssl_ca_file: pem_path,
                           verify_ssl: true,
                           password: pass
                           )
puts reply
```

can someone please help me out with this ?

**Comment by ab** [comment]
You'll want to pass `ssl_client_cert` and `ssl_client_key` to match the behavior of curl.

You can read them from the same file if the X.509 certificate and RSA private key are both in there:

```rb
require 'openssl'

require 'rest-client'
keypass = 'test'
client_key = OpenSSL::PKey::RSA.new(File.read('client.key'), keypass)
client_cert = OpenSSL::X509::Certificate.new(File.read('client.crt'))
  
response = RestClient::Request.execute(
  method: :get,
  url: url,
  ssl_client_cert: client_cert,
  ssl_client_key: client_key,
)

**Comment by scratchoo** [comment]
@ab I am using your suggested answer but getting:

usr/lib/ruby/3.0.0/openssl/pkey.rb:348:in `initialize': incorrect pkey type: id-ecPublicKey (OpenSSL::PKey::RSAError)

do you have any idea?

**Comment by edusurf10** [comment]
Hello, fallow my request:

@cert_path = 'config/certs/certificate.crt'
@keys_path = 'config/certs/private_key.key'
@cert_pass = Rails.application.credentials.pag[:cert_password]
@certificate = OpenSSL::X509::Certificate.new(File.read(@cert_path))
@certificate_keys = OpenSSL::PKey::RSA.new(File.read(@keys_path), @cert_pass)

response = RestClient::Resource.new(
          "#{@api_url}/test",
          ssl_client_cert: @certificate,
          ssl_client_key: @certificate_key,
          headers: request_headers
        ).post(payload.to_json)
        
        i received error:
        SSL_connect returned=1 errno=0 peeraddr=host-ip:443 state=error: sslv3 alert bad certificate
        
using postman this crt and key working.
