### ISSUE TITLE
Can't get Proxy-Authorization header to work... string problems?

### ISSUE THREAD

**Issue by maxiedaniels** [rest-client/rest-client#705]
When I successfully authenticate through proxy via curl and view in Wireshark as a test, I'm showing:

```
Hypertext Transfer Protocol
 GET http://mysite.com HTTP/1.1\r\n
 Host: mysite.com\r\n
 Proxy-Authorization: Basic myencodedstring
```

However, when I try and do the same header in rest-client, as below:
`response = RestClient.get('http://mysite.com', headers: { 'Proxy-Authorization' => 'Basic myencodedstring})`

I'm showing this in Wireshark:

```
Hypertext Transfer Protocol
 GET http://mysite.com HTTP/1.1\r\n
 Headers: {"Proxy-Authenticate"=>"Basic", "Proxy-Authorization"=>"Basic myencodedstring"}\r\n
```

The authorization doesn't work via rest-client, and the obvious difference to me is the format... rest-client is showing 'Headers:' and the parameters have actual quotes around them..
Am I missing something? I've tried using various formats of headers, but nothing works.

**edit**

To make sure I wasn't crazy, I quickly tried this same thing in HTTParty and it worked like a charm.. so I'm very lost.

**Comment by ab** [comment]
The API for `RestClient.get` is:

```
RestClient.get(url, headers={})
```

This design predates Ruby keyword arguments, so your usage is creating an HTTP header called `Headers` and coercing the hash into a string.

You probably want `RestClient::Request.execute()` instead if you want to pass the headers all in a single hash and to pass other arguments. Or just pass the headers directly without nesting in `RestClient.get(url, {'Proxy-Authorization' => '...'})`.
