### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by obfuscoder** [rest-client/rest-client#707]
There have been no commits for almost two years. A lot of pending issues and pull requests are not getting dealt with. We have been using this gem for quite some time now, but are worried that it has been abandoned by the authors.

Could you please state whether this project is going to get some love some time or are you looking for someone else to maintain it?

**Comment by cabe56** [comment]
Fork, merge a couple of PRs from contributors that have put in PRs before and comment on each letting them know you've reactivated the project :D

Just an idea, not meaning to dis you.

**Comment by z64** [comment]
Certainly, anyone can try to do that; but it would be responsible of the current listed maintainers to give an updated status so users can make informed decisions about whether they need to use another gem or fork.

Additionally, `rest-client` is no small project.. there is a lot of code here that takes a lot of knowledge to maintain properly - not only for Ruby correctness, but things like security behaviors as well.

![image](https://user-images.githubusercontent.com/6119032/59372481-9a0ec680-8d15-11e9-9606-b36fe8131289.png)

There are *tons* of packages, and even more users of those packages, who rely on the code in this repo.

**Comment by cabe56** [comment]
Was just trying to give an option given the mantainers are not responding to the issue.

I found contact info on their github profiles, jic anyone wants to contact them:
1. [Matt Manning](https://github.com/mattmanning): matt.manning@gmail.com
2. [Larry Gilbert](https://github.com/L2G): larry+github@l2g.to
3. [Andy Brody](https://github.com/ab)

**Comment by gingerlime** [comment]
I just saw a new release, so hope it means the project is still alive and kicking? :)

**Comment by ab** [comment]
Hi folks,

2.1.0 was released yesterday, at long last! As you have seen, maintenance has been dormant for a while now. I'd been meaning for ages to find new maintainers to hand things off to, but never found the time.

If folks are interested in contributing more actively, please let me know. Especially in light of #713, I think it makes sense to codify some more formal expectations around maintainership.

**Comment by z64** [comment]
Thank you for all the updates @ab. If I may make a suggestion, opening a (pinned?) issue would be a good idea if the maintenance status is still unstable, adding a note to `README.md` if the issue is less pressing, or drafting a `CONTRIBUTING.md` guide as is standard in many repos these days. The latter would be good to have regardless :smiley_cat:
