### ISSUE TITLE
RestClient::NotFound: 404 Not Found (misleading error)

### ISSUE THREAD

**Issue by Faisal-nfl** [rest-client/rest-client#708]
I am sending email with mailgun, there was issue with domain name but it kept on giving error 
"RestClient::NotFound: 404 Not Found", 
after hours of reinstalling and different stuff, finally realized that the error was misleading and correction of domain fixed the issue

**Comment by phoebeclarke** [comment]
We're experiencing the same error trying to use RestClient version 2.0.2. Could you give us any more detail on how you fixed it? Correction of which domain?

**Comment by Faisal-nfl** [comment]
I add subdomain on mailgun like 'mail.abc.com' but was using abc.com while sending email
```
config.action_mailer.mailgun_settings = {
    api_key: ENV['MAILGUN_API_KEY'],
    domain: 'abc.com',
  }
```
changing to this worked for me
```
config.action_mailer.mailgun_settings = {
    api_key: ENV['MAILGUN_API_KEY'],
    domain: 'mail.abc.com',
  }
```

not sure, if you are facing same thing or noit

**Comment by phoebeclarke** [comment]
Ah no, we're facing a very different issue 😅I appreciate you sharing your solution though.
