### ISSUE TITLE
Corrupted response body instead of JSON response after upgrade rest-client from 2.0.2 to 2.1.0

### ISSUE THREAD

**Issue by ArturT** [rest-client/rest-client#722]
I use Ruby 2.6.3. When I use rest-client 2.0.2 then request to Heroku API returned valid json in `response.body`. After upgrade to rest-client 2.1.0 I get weird string `\x1F\x8B\....` instead of valid JSON. Response.code is 200. So it seems Heroku API returned successful response.

> 2.6.3 :011 > response = RestClient.get "https://api.heroku.com/teams/a43a3169-7085-4e10-9d2c-029bd832ce62/members", "Accept"=>"application/vnd.heroku+json; version=3", "Authorization"=>"Bearer c01c7302-0248-4625-9719-8a47c1198030", "Content-Type"=>"application/json", "User-Agent"=>"rest-client/2.1.0 (darwin18.2.0 x86_64) ruby/2.6.3p62"
>  => <RestClient::Response 200 "\x1F\x8B\b\x00#\xE8\x7F]\x00\x03\x9C...">

> 2.6.3 :012 > response.body
>  => "\x1F\x8B\b\x00#\xE8\x7F]\x00\x03\x9C\x90\xC1N\xC4 \x10\x86_\xC5p\xEEl\x98\xB6P\xCAi}\x87=i\xCC\x06\x180Mhi\xD8\xD6D\xCD\xBE\xBB4z16n\xF4\b?\xF3\xCF\xC7\xF7\xF8\xCE\x06b\x9Aq\x12\\)\xE9\xA0C\xEC\xA0\xED\x85\x81\xBE\xB6=H\xEE\xB9\xB2\r)#ZV1\x97\xBDY<\x9D\xCDRfj\x8E=\xF0\x0EP\x9D\xB0\xD1X\xEB\x96?\x947~4C,\xB1\xC9\xCB\x9A\x0FK~K\xF31\xC6\xF90\xC7\x12\x06O>o\x15L\a\x13/\xBE*\xEB\xFD\xB4\f\xCB\xEBy\xCE\xE9\xA5\x1C2\xD3\xD3\x1Ac\xC5r\x8A\xBE\xD4\xB8\x14\xA3\xB1\xA9\f\xA5\\\n\xD6\x99n\x12\xAC\x97\xAD\xE5o?\xFB\x95z2\xE3\x86r\xBFew\xA7-c\xD7k\xF5\xB5@z\xDEQc=`\xE7\x10Z\x92-Xl8\xF4\xD8\x88>8\xA2 \xFD\x8E\xBAB\x8D\x80\xFC\x84\xA8\xB9\xD2\xB5\xF8\xA1\xEE\x93\xE1y\xBB:\xB84\xFEK\x9E\xA1q\x98v\xAC\xED-\xFFf\xCD*\xA9\xB8C\t\xDC\v\tm\b\x0E,\xF7\x0E\x14*\n\xB5\xA3\x86D\xB8\r\xBC\xEB\xED\xE9\x03\x00\x00\xFF\xFF\x03\x00\xA8\xD2\x1F\x15t\x02\x00\x00"

This Heroku API is private so I can't share a reproducible example. In the above code, there is expired access token for `Authorization` header. 

Did anyone notice similar issue for any other of your requests in rest-client 2.1.0?

I noticed rest-client 2.1.0 depends on http-accept gem now:

```
   rest-client (2.1.0)
      http-accept (>= 1.7.0, < 2.0)
```

I tried to check [http-accept](https://github.com/socketry/http-accept) gem to see if it can parse `application/vnd.heroku+json; version=3` but it seems to work fine.

```ruby
HTTP::Accept::MediaTypes.parse('application/vnd.heroku+json; version=3')
```

I'm not sure if this is bug directly in rest-client or somehow connected to http-accept.

**Comment by krimsonkla** [comment]
I have something similar, but with XML being garbled. Everything works fine in 2.0.2
![Screen Shot 2019-09-24 at 10 55 46 AM](https://user-images.githubusercontent.com/354469/65537323-decfff00-deb9-11e9-86f5-5ce85323004d.png)

The issue appears to be right here
https://github.com/rest-client/rest-client/compare/v2.0.2...v2.1.0#diff-3724e1adc91ded3d8e979d73f91f1b1eR828

request.rb no longer decodes the response body.

**Comment by chenillen** [comment]
Downgrade only?

**Comment by brodygov** [comment]
#597

RestClient 2.1 switched to using Net::HTTP's built-in decoding of HTTP transport encoding, so if it's not automatically handled by Net:HTTP (which you would normally expect it to be), then you'll need to decompress the content yourself.

**Comment by maguri** [comment]
Same issue here:

rest-client 2.0.1:
```ruby
ActionController::HttpAuthentication::Basic::user_name_and_password(request)
["user", "password"] # fake of course ;)
```
upgrade to rest-client 2.1.0:

```ruby
ActionController::HttpAuthentication::Basic::user_name_and_password(request)
["\xB6\x89\x1E\...k\xAE\x9B\xDF__\xD7W\x9A\xF7~\x1A\xEFov\xD9\xAE\xFA\xF3G=\xE5\xAF6\xEBO\x1E\xDF^\x9C\...}\xBA\xDB\xC7\xB6"]
```

Thanks @brodygov, this issue helped me to fix my bug.

**Comment by ArturT** [comment]
@maguri How you decompress the content? Can you share some code examples? Thanks.

**Comment by maguri** [comment]
Hi @ArturT I simply improved my api using token instead of basic http auth (it was an old code decision and this issue encourage the team to finally improve the code).

so I replaced this in the client part:
```ruby
authenticate_or_request_with_http_basic do |username, password|
  ...
end
```
for this:
```ruby
authenticate_or_request_with_http_token do |token|
  ...
end
```

**Comment by mhgoldman** [comment]
I'm also seeing this issue with RestClient::Resource after upgrading to 2.1.

I saw that according to https://github.com/ruby/ruby/commit/ddddf044b27c87b0b2d5b31bb1ed2277f211ec1e, Net::HTTP's decoding logic is disabled automatically if an Accept-Encoding header is found. I'm certain I was not setting Accept-Encoding in my code. But sure enough, when I tried instantiating my RestClient::Resource with `headers: { accept_encoding: nil }`, that seemed to fix my problem. Setting the value to `*` also works, while setting it to `gzip` seems to have the same effect as not setting it at all.

So it seems that somehow, unless I override it, `accept_encoding` is being set to a value that results in the decoding being disabled. I haven't yet figured out how that's happening -- maybe one of my gems is doing something weird -- but I thought I'd mention it here in case it helps somebody.

**Comment by ArturT** [comment]
@mhgoldman Thanks for sharing this. I tried to pass `headers` as below:

```ruby
{
          #'Accept-Encoding' => '*',
          #'Accept-Encoding' => 'gzip, deflate',
          #accept_encoding: nil,
          accept_encoding: '*',
}
```

To `RestClient.get(url, headers)` but non of it make the `response.body` readable. I still see  messed up response like `\x1F\x8B\b\x00#\xE...` :(

**Comment by anke1460** [comment]
@ArturT  Thanks for fixed my bug of yesterday that raise error

>  Zlib::DataError (incorrect header check)

 I used this way to work fine.

> res = RestClient.post(uri, {content: content"}.to_json, {accept_encoding: '*'})

**Comment by ArturT** [comment]
I fixed my issue by using headers:

```
{  'Accept-Encoding' => '' }
```

Thanks to that Heroku API returns pure JSON instead of binary response.

**Comment by timrwilliams** [comment]
In addition to earlier solutions you can decode the GZipped response:

```
sio = StringIO.new(  response.body )
gz = Zlib::GzipReader.new( sio )
decoded_body = gz.read()
```
