### ISSUE TITLE
Incorrect redirect processing

### ISSUE THREAD

**Issue by jfieber** [rest-client/rest-client#8]
When following redirects, RestClient blindly rewrites the original request into a GET request.  The HTTP 1.1 specification explicitly forbids automatic redirect for most cases if the original request is not a GET or HEAD.

From http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html :

"If the 301 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.

Note: When automatically redirecting a POST request after receiving a 301 status code, some existing HTTP/1.0 user agents will erroneously change it into a GET request."

**Comment by tit** [comment]
But why rest-client return code 200 and not 301?
```sh
$ ruby -r rest-client -e 'puts RestClient.get("http://httpbin.org/status/301").code'
200

$ gem list rest-client
*** LOCAL GEMS ***
rest-client (1.6.8)
```

**Comment by ab** [comment]
@tit RestClient is showing you the response _after_ following the redirection and making a second request.

You can use something like this to see what happens without following redirection:
```
RestClient::Request.execute(method: :get, url: 'http://httpbin.org/status/301', max_redirects: 0)
```

**Comment by ab** [comment]
The upcoming 2.0 release of rest-client will also expose a history of responses on redirected requests.

```
>> r = RestClient.get('http://httpbin.org/status/301')
=> <RestClient::Response 200 "{\n  \"args\":...">
>> r.history
=> [<RestClient::Response 301 "">, <RestClient::Response 302 "<!DOCTYPE H...">]
```

**Comment by tit** [comment]
max_redirects don't work. :(
```
irb -r rest-client
irb(main):001:0> RestClient::Request.execute(method: :get, url: 'http://httpbin.org/status/301', max_redirects: 0)
RestClient::MaxRedirectsReached: Maximum number of redirect reached: 
	from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.6.8/lib/restclient/abstract_response.rb:71:in `follow_redirection'
	from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.6.8/lib/restclient/abstract_response.rb:41:in `return!'
	from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.6.8/lib/restclient/request.rb:269:in `process_result'
	from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.6.8/lib/restclient/request.rb:212:in `block in transmit'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in `transmit'
	from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in `execute'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'
```
